export interface IntegrationsImplementationGuidance {
  label: string;
  text: string;
}

export const IMPLEMENTATION_GUIDANCE: IntegrationsImplementationGuidance[] = [
  { label: "Platform composition", text: "Every one of these 12 components is a pure re-export over an already-certified Workflow or Operational component — checked directly against the platform's own composition rules before writing each file, and in every case an existing component's prop surface already covered the need with no Integrations-specific field required. IntegrationsSync (= SyncStatusPanel) is this package's first real Platform-tier consumer of Status & Health's own sync-status component." },
  { label: "Workflow integration", text: "IntegrationsMappings composes Dependency & Relationship Views' own RelationshipView directly, checked against DependencyGraph/DependencyEdge and confirmed the better fit — a field mapping is a two-way peer correspondence (RelationshipEdge defaults to bidirectional), not a one-way dependency (DependencyEdge defaults to forward). The identical composition Product Platform's own ProductProviderMappings already established. IntegrationsInspector composes State Machine directly for a single connection's own lifecycle." },
  { label: "Operational integration", text: "IntegrationsProviders composes Operational's own DataGrid directly for a browsable, caller-defined-column registry, while IntegrationsConnections composes the narrower ProviderHealthPanel preset (a hard-locked name/status/latency/uptime row) for per-connection health — checked directly against each other and confirmed distinct: a registry needs heterogeneous, caller-defined columns a health preset can't express, while a connection-status view is exactly the uniform row ProviderHealthPanel already locks in." },
  { label: "Provider presentation", text: "IntegrationsProviders does not implement real provider discovery, OAuth flows, or marketplace API calls — it renders whatever provider rows and columns the caller supplies through Data Grid's own controlled props. Whether a provider is actually reachable is Business Feature logic, not something this platform component decides." },
  { label: "Connection lifecycle", text: "IntegrationsConnections and IntegrationsInspector do not implement real connection-state persistence, credential storage, or reconnect logic — they render whatever ProviderHealthRow/StateInspectorProperty values the caller supplies. Establishing, refreshing, or revoking a real connection is Business Feature logic." },
  { label: "Mapping management", text: "IntegrationsMappings' own children slot is where RelationshipNode/RelationshipEdge content belongs for each field correspondence — the shell holds no business logic about schema validation, type coercion, or transform execution. Whether a mapping is actually valid against two real schemas is Business Feature logic." },
  { label: "Synchronization monitoring", text: "IntegrationsSync's own sources prop expects caller-supplied SyncSource objects already computed — it does not poll, schedule, or execute a sync job itself, the same read-only, display-only contract SyncStatusPanel's own docstring already establishes." },
  { label: "Diagnostics presentation", text: "IntegrationsDiagnostics' own issues prop expects caller-supplied HealthIssueEntry objects already ranked — it does not run diagnostic checks, classify errors, or re-sort by severity itself, the same read-only contract every diagnostics/issue-list component in this tier already follows." },
];
