export interface IntelligenceImplementationGuidance {
  label: string;
  text: string;
}

export const IMPLEMENTATION_GUIDANCE: IntelligenceImplementationGuidance[] = [
  { label: "Platform composition", text: "Every one of these 12 components is a pure re-export over an already-certified Workflow or Operational component — checked directly against Platform Rules (defined in DS-4.1) before writing each file, and in every case an existing component's prop surface already covered the need with no Intelligence-specific field required. The same zero-new-wrapper-code precedent every prior Platform package already established. Unlike prior packages, this one leans heavily on Dashboard Widget System (DS-2.5.9) and Status & Health System (DS-2.5.7) rather than Workflow's own Pipeline/Approval families, since recommendations/health/diagnostics/insights are exactly what those two Operational systems were already built for." },
  { label: "Workflow integration", text: "IntelligenceInspector composes State Machine directly for a single analysis' own lifecycle. IntelligenceMetrics/IntelligenceSummary compose Pipeline Components directly, the same precedent-consistent pair every prior Platform Metrics/Summary already used, over Dashboard Widget System's own KPIWidget (considered as an alternative but not chosen, to stay consistent with the established pair)." },
  { label: "Operational integration", text: "IntelligenceRecommendations composes Dashboard Widget System's own RecommendationWidget directly. IntelligenceHealth composes Status & Health System's own HealthPanel directly — chosen over the tile-shaped HealthWidget because Intelligence's own Inspector-shell workspace context matches HealthPanel's own design intent, not a dashboard-tile context. IntelligenceDiagnostics composes Status & Health's own HealthIssueList directly. IntelligenceInsights composes Dashboard Widget System's own ChartWidget directly. IntelligenceOpportunities composes Operational's own DataGrid directly, the same tabular reuse Commerce and Publishing Platform's own components already established — five of twelve components reusing Operational directly, more than any prior Platform package." },
  { label: "Health presentation", text: "IntelligenceHealth does not implement real health-check, monitoring, or scoring logic — it renders whatever score/metrics/issues/recommendations the caller supplies through HealthPanel. Whether a system is actually healthy is Business Feature logic, not something this platform component decides." },
  { label: "Recommendation presentation", text: "IntelligenceRecommendations does not implement recommendation generation, ranking, or scoring — it renders whatever RecommendationEntry[] the caller supplies through RecommendationWidget. Which recommendations actually surface is Business Feature logic." },
  { label: "Diagnostics", text: "IntelligenceDiagnostics does not implement root-cause analysis — it renders whatever HealthIssueEntry[] the caller supplies through HealthIssueList, already ranked by the caller; this component never re-sorts by severity." },
  { label: "Insight organization", text: "IntelligenceInsights does not implement data aggregation or trend calculation — it renders whatever ChartWidgetDatum[] the caller supplies through ChartWidget. Per Platform Component Architecture's own explicit scope boundary for the Intelligence platform template: \"the actual analytics computation, ML inference, and data pipeline stay in Business Features... Platform only owns how an insight is displayed and navigated, not how it's computed.\"" },
];
