export interface AdminImplementationGuidance {
  label: string;
  text: string;
}

export const IMPLEMENTATION_GUIDANCE: AdminImplementationGuidance[] = [
  { label: "Platform composition", text: "Every one of these 12 components is a pure re-export over an already-certified Workflow or Operational component — checked directly against Platform Rules (defined in DS-4.1) before writing each file, and in every case an existing component's prop surface already covered the need with no Admin-specific field required. AdminEnrollment (= ApprovalStage) is this package's first real Platform-tier consumer of Approval & Review's own stage component." },
  { label: "Workflow integration", text: "AdminAudit composes State Machine's own StateHistory directly for a chronological admin-action log, the same reuse Publishing Platform's own PublishingHistory already established over the confusingly-named WorkflowTimeline. AdminEnrollment composes Approval & Review's own ApprovalStage, checked directly against Pipeline Components' own PipelineStage and confirmed the better fit — enrollment is a process with individually accept/reject/pending steps, not just a generic titled stage group. AdminInspector composes State Machine directly for a single item's own lifecycle." },
  { label: "Operational integration", text: "AdminUsers and AdminPermissions both compose Operational's own DataGrid directly — checked against PropertyPanel for Permissions specifically, and DataGrid was confirmed the better fit since \"Role Management\" is a roster (many roles, tabular), not a single role's structured field editor. AdminConfiguration composes Operational's own PropertyPanel directly for structured settings editing, the same family CommercePricing already composed." },
  { label: "Permission presentation", text: "AdminPermissions does not implement real access-control checks or permission-evaluation logic — it renders whatever role/permission columns and rows the caller supplies through Data Grid's own controlled props. Whether a role actually grants access to something is Business Feature logic, not something this platform component decides." },
  { label: "Configuration management", text: "AdminConfiguration's own children slot is where PropertyRow/PropertyToggle/PropertySelect content belongs for system settings — the same \"children slot for extra context\" pattern every Property/Inspector Panel in this tier already uses, rather than a second settings-specific editor. It does not persist configuration itself." },
  { label: "Audit presentation", text: "AdminAudit's own entries prop expects caller-supplied StateHistoryEntry objects already in order — it does not fetch, persist, or re-sort audit data itself, the same read-only contract every history component in this tier already follows." },
  { label: "Enrollment workflow", text: "AdminEnrollment's own children slot is where ApprovalStep content belongs for each onboarding stage — the shell holds no business logic about step ordering, gating, or approval-decision evaluation. Whether an enrollment step actually passes its own approval gate is Business Feature logic." },
];
