/**
 * @jheavner95/design — root entry point.
 *
 * Shared presentation primitives only: no business logic, no API clients,
 * no repository/auth/routing state, no application orchestration.
 *
 * A handful of names collide across the source folders this barrel
 * combines. Six of those are intentional cross-family re-exports of the
 * exact same component (documented as "shared ownership" in their own
 * source comments) — only the canonical copy is re-exported here. One
 * (`PropertyEditor`) is a genuine second implementation specific to the
 * operational inspector family, so it is re-exported under a distinct
 * name (`InspectorPropertyEditor`) instead of being dropped.
 */

// Framework capability types. Design targets React and no framework; the
// capabilities a framework would otherwise provide — link navigation, image
// optimisation — are injected as props, and these are the types for doing so.
// See @/framework/types for why props rather than context.
export type { LinkComponent, LinkComponentProps, ImageComponent, ImageComponentProps } from "@/framework";

// Core UI primitives
export {
  Badge,
  type BadgeProps,
  Body,
  type BodyProps,
  Button,
  type ButtonProps,
  Caption,
  type CaptionProps,
  Card,
  type CardProps,
  Checkbox,
  type CheckboxProps,
  Combobox,
  type ComboboxProps,
  type ControlSize,
  CTAGroup,
  type CTAGroupProps,
  Display,
  Expandable,
  type ExpandableProps,
  Eyebrow,
  type EyebrowProps,
  FeatureCard,
  type FeatureCardProps,
  FieldGroup,
  type FieldGroupLayout,
  type FieldGroupProps,
  type FieldStatus,
  FilterBar,
  type FilterBarProps,
  type FilterChip,
  FormField,
  type FormFieldProps,
  GlassPanel,
  type GlassPanelProps,
  type GlyphSize,
  Heading,
  type HeadingProps,
  IconButton,
  type IconButtonProps,
  type IconButtonSize,
  INTERACTIVE_CARD_CLASSES,
  Metadata,
  RadioGroup,
  type RadioGroupProps,
  type RadioOption,
  SearchInput,
  type SearchInputProps,
  SectionBadge,
  type SectionBadgeProps,
  SectionHeader,
  type SectionHeaderProps,
  SegmentedControl,
  type SegmentedControlOption,
  type SegmentedControlProps,
  Select,
  SelectableCard,
  type SelectableCardProps,
  type SelectOption,
  type SelectProps,
  Skeleton,
  type SkeletonProps,
  type SkeletonVariant,
  Slider,
  type SliderProps,
  StatCard,
  type StatCardProps,
  type StatusTone,
  SurfacePanel,
  type SurfacePanelProps,
  Textarea,
  type TextareaProps,
  TextInput,
  type TextInputProps,
  ToggleSwitch,
  type ToggleSwitchProps,
} from "@/components/ui";

// Layout primitives. Before DH-2 these were imported from their individual
// source files rather than the "@/components/layout" barrel, because that
// barrel also re-exported GlobalNav and Footer — documentation-site app
// shell chrome that must never ship — and importing anything from the
// barrel pulled them in whether or not they were re-exported onward.
// GlobalNav and Footer now live in the documentation application, so the
// barrel is safe. The per-file imports are kept deliberately: they name the
// exact public surface, which `export *` would not, and widening the
// published API is not DH-2's business.
export { Container, type ContainerSize, type ContainerProps } from "@/components/layout/Container";
export { PageShell, type PageShellProps } from "@/components/layout/PageShell";
export {
  SectionShell,
  type SectionShellProps,
  type SectionShellBackground,
  type SectionShellSpacing,
} from "@/components/layout/SectionShell";
export {
  ContentColumns,
  type ContentColumnsProps,
  type ContentColumnsRatio,
  type ContentColumnsGap,
  type ContentColumnsAlign,
} from "@/components/layout/ContentColumns";
export { CardGrid, type CardGridProps, type CardGridColumns } from "@/components/layout/CardGrid";
export { Stack, type StackProps, type StackGap, type StackAlign, type StackJustify } from "@/components/layout/Stack";
export {
  Inline,
  type InlineProps,
  type InlineGap,
  type InlineAlign,
  type InlineJustify,
} from "@/components/layout/Inline";
export { Grid, type GridProps, type GridStrategy, type GridGap } from "@/components/layout/Grid";
export { Cluster, type ClusterProps } from "@/components/layout/Cluster";
export {
  Surface,
  type SurfaceProps,
  type SurfaceElevation,
  type SurfacePadding,
} from "@/components/layout/Surface";
export { Panel, type PanelProps } from "@/components/layout/Panel";
export {
  Workspace,
  WorkspaceHeader,
  WorkspaceToolbar,
  WorkspaceBody,
  WorkspaceNavigation,
  WorkspaceContent,
  WorkspaceInspector,
  WorkspaceFooter,
  workspaceDensityPadding,
  workspaceDensityHeaderHeight,
  type WorkspaceProps,
  type WorkspaceHeaderProps,
  type WorkspaceToolbarProps,
  type WorkspaceBodyProps,
  type WorkspaceNavigationProps,
  type WorkspaceContentProps,
  type WorkspaceInspectorProps,
  type WorkspaceFooterProps,
  type WorkspaceDensity,
} from "@/components/layout/Workspace";
export {
  SplitView,
  SplitPane,
  SplitDivider,
  type SplitViewProps,
  type SplitPaneProps,
  type SplitDividerProps,
  type SplitOrientation,
} from "@/components/layout/SplitView";
export { ScrollArea, type ScrollAreaProps, type ScrollDirection } from "@/components/layout/ScrollArea";
export { Separator, type SeparatorProps, type SeparatorOrientation } from "@/components/layout/Separator";
export {
  DescriptionList,
  type DescriptionListProps,
  type DescriptionListItem,
  type DescriptionListLayout,
} from "@/components/layout/DescriptionList";

// Form primitives — FormField is dropped here: it's the exact same
// component already re-exported from "@/components/ui" above.
export {
  Form,
  type FormProps,
  FormSection,
  type FormSectionProps,
  FormRow,
  type FormRowProps,
  FormActions,
  type FormActionsProps,
  FieldLabel,
  type FieldLabelProps,
  FieldHelp,
  type FieldHelpProps,
  FieldError,
  type FieldErrorProps,
  type FieldMessageTone,
  RequiredIndicator,
  InputField,
  type InputFieldProps,
  TextareaField,
  type TextareaFieldProps,
  SelectField,
  type SelectFieldProps,
  ComboboxField,
  type ComboboxFieldProps,
  type ComboboxOption,
  CheckboxField,
  type CheckboxFieldProps,
  RadioGroupField,
  type RadioGroupFieldProps,
  SwitchField,
  type SwitchFieldProps,
  SliderField,
  type SliderFieldProps,
  DatePickerField,
  type DatePickerFieldProps,
  FileUploadField,
  type FileUploadFieldProps,
  PropertyEditor,
  type PropertyEditorProps,
  type PropertyEditorField,
  ValidationSummary,
  type ValidationSummaryProps,
  type ValidationSummaryItem,
  UnsavedChangesBanner,
  type UnsavedChangesBannerProps,
  FormDivider,
  type FormDividerProps,
} from "@/components/form";

// Feedback primitives — Skeleton and ValidationSummary are dropped here:
// both are the exact same components already re-exported above (from
// "@/components/ui" and "@/components/form" respectively).
export {
  Alert,
  type AlertProps,
  FEEDBACK_TONE_ICON,
  FEEDBACK_TONE_TEXT,
  FEEDBACK_TONE_BG,
  feedbackRole,
  type FeedbackTone,
  Banner,
  type BannerProps,
  InlineMessage,
  type InlineMessageProps,
  ToastProvider,
  type ToastProviderProps,
  useToast,
  type ToastOptions,
  Notification,
  type NotificationProps,
  LiveRegionProvider,
  useAnnounce,
  EmptyState,
  type EmptyStateProps,
  type EmptyStateTone,
  LoadingState,
  type LoadingStateProps,
  Spinner,
  type SpinnerProps,
  type SpinnerSize,
  ProgressBar,
  type ProgressBarProps,
  type ProgressTone,
  ProgressRing,
  type ProgressRingProps,
  StatusIndicator,
  type SystemStatus,
  SuccessState,
  type SuccessStateProps,
  WarningState,
  type WarningStateProps,
  ErrorState,
  type ErrorStateProps,
  InfoState,
  type InfoStateProps,
} from "@/components/feedback";

// Navigation primitives — SegmentedControl is dropped here: the exact
// same component already re-exported above (from "@/components/ui").
// Link rendering is injected: NavigationItem and Breadcrumbs take an
// optional `linkComponent` and default to a plain <a>. Until DH-3 they
// imported next/link and next/navigation directly.
export {
  NavigationItem,
  NavigationCollapsedContext,
  useNavigationCollapsed,
  type NavigationItemProps,
  NavigationGroup,
  type NavigationGroupProps,
  NavigationDivider,
  type NavigationDividerProps,
  type NavigationDividerOrientation,
  NavigationSection,
  type NavigationSectionProps,
  Tabs,
  type TabsProps,
  TabsList,
  type TabsListProps,
  Tab,
  type TabProps,
  TabPanel,
  type TabPanelProps,
  Breadcrumbs,
  type BreadcrumbsProps,
  type BreadcrumbItem,
  Pagination,
  type PaginationProps,
  type PaginationVariant,
  Stepper,
  type StepperProps,
  type Step,
  type StepStatus,
  SideNavigation,
  type SideNavigationProps,
  TopNavigation,
  type TopNavigationProps,
  type TopNavigationItemDef,
  NavigationRail,
  type NavigationRailProps,
  type NavigationRailItemDef,
  TreeNavigation,
  type TreeNavigationProps,
  type TreeNode,
  CommandNavigation,
  type CommandNavigationProps,
  ContextNavigation,
  type ContextNavigationProps,
  type ContextNavigationLink,
} from "@/components/navigation";

// Overlay primitives
export {
  type AnchorAlign,
  type AnchorPlacement,
  CommandPalette,
  type CommandPaletteItem,
  type CommandPaletteProps,
  ConfirmDialog,
  type ConfirmDialogProps,
  type ConfirmTone,
  Dialog,
  DialogBody,
  DialogClose,
  type DialogCloseProps,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  type DialogProps,
  type DialogSize,
  DialogTitle,
  Drawer,
  type DrawerEdge,
  type DrawerProps,
  Menu,
  MenuItem,
  type MenuItemProps,
  type MenuProps,
  Popover,
  type PopoverProps,
  Portal,
  type PortalProps,
  Tooltip,
  type TooltipProps,
  useAnchoredPosition,
} from "@/components/overlay";

// Table primitives
export {
  ResponsiveRulesTable,
  type ResponsiveRulesTableColumn,
  type ResponsiveRulesTableProps,
  type ResponsiveRulesTableRow,
  type SortDirection,
  Table,
  TableActionCell,
  type TableActionCellProps,
  TableBody,
  type TableBodyProps,
  TableCell,
  type TableCellProps,
  type TableDensity,
  TableEmptyState,
  type TableEmptyStateProps,
  TableFooter,
  type TableFooterProps,
  TableHead,
  TableHeader,
  type TableHeaderProps,
  type TableHeadProps,
  TableLoadingState,
  type TableLoadingStateProps,
  type TableProps,
  TableRow,
  type TableRowProps,
  TableSelectionCell,
  type TableSelectionCellProps,
  TableStatusCell,
  type TableStatusCellProps,
  TableToolbar,
  type TableToolbarProps,
  useTableDensity,
} from "@/components/table";

// Metadata primitives — DescriptionList/DescriptionListItem are dropped
// here: the exact same component already re-exported above (from
// "@/components/layout").
export {
  MetadataGroup,
  type MetadataGroupProps,
  MetadataRow,
  type MetadataRowProps,
  type MetadataRowLayout,
  MetadataField,
  type MetadataFieldProps,
  MetadataValue,
  type MetadataValueProps,
  MetadataLabel,
  type MetadataLabelProps,
  IdentityBlock,
  type IdentityBlockProps,
  PropertyGroup,
  type PropertyGroupProps,
  PropertySection,
  type PropertySectionProps,
  RelationshipList,
  type RelationshipListProps,
  type RelationshipItem,
  StatusSummary,
  type StatusSummaryProps,
  type StatusSummaryItem,
  HealthSummary,
  type HealthSummaryProps,
  type HealthMetric,
  type HealthState,
  StatGroup,
  type StatGroupProps,
  type StatGroupItem,
  TagCollection,
  type TagCollectionProps,
  EmptyMetadata,
  type EmptyMetadataProps,
  LoadingMetadata,
  type LoadingMetadataProps,
} from "@/components/metadata";

// Motion — React composition components (FadeIn/SlideUp/StaggerGroup/etc.)
export {
  activeNodeVariants,
  AnimatedCounter,
  type AnimatedCounterProps,
  FadeIn,
  type FadeInProps,
  fadeInVariants,
  MotionPreferenceProvider,
  type MotionPreferenceProviderProps,
  progressLineVariants,
  PulseStatus,
  type PulseStatusProps,
  type PulseTone,
  pulseVariants,
  ScaleIn,
  type ScaleInProps,
  scaleInVariants,
  SlideUp,
  type SlideUpProps,
  slideUpVariants,
  staggerContainerVariants,
  StaggerGroup,
  type StaggerGroupProps,
  StaggerItem,
  type StaggerItemProps,
  useMotionPreference,
} from "@/components/motion";

// Note: "@/motion" (the lower-level engine — tokens, transition/stagger/
// sequence builders, and the Fade/Slide/Scale/Expand/Collapse/Crossfade/
// Pulse/Highlight/Progress/ConnectorFlow/PublishFlow/QueueFlow primitives
// it's built from) is a required transitive dependency of several folders
// above (SelectableCard, ProgressBar, Toast, Popover, CommandPalette,
// Drawer, Menu, Tooltip, Dialog all import from it directly) and remains
// bundled — but is deliberately NOT re-exported here. RM-4 exposed it
// publicly (with its Stagger/StaggerGroup/StaggerItem renamed to
// Engine-prefixed names to avoid colliding with "@/components/motion"'s
// own Stagger); RM-5.5's public API review reclassified it as internal:
// it's a low-level implementation primitive set (resolveDuration,
// transition, stagger, sequence, etc.) that consumers don't need
// directly, not a stable public surface. Removing it also removes the
// collision, so "@/components/motion"'s Stagger/StaggerGroup/StaggerItem
// no longer need any override.

// Operational component family. Four names collide with folders already
// exported above, resolved as follows: StatusSummary is dropped (exact
// same component already re-exported from "@/components/metadata");
// PropertyGroup/PropertySection are dropped (both are this family's own
// re-exports of InspectorGroup/InspectorSection, which are already
// exported below under their real names — re-exporting them a second
// time under the "PropertyGroup"/"PropertySection" alias would just
// duplicate InspectorGroup/InspectorSection while also colliding with
// metadata's real, independent PropertyGroup/PropertySection above);
// PropertyEditor, FilterBar, and FilterChip are genuine second
// implementations specific to this family (an inspector field editor, a
// SearchField-based filter bar, and a real filter-chip component,
// distinct from the form system's PropertyEditor and the ui system's
// FilterBar/FilterChip type) and are re-exported under distinct names.
export {
  DataGrid,
  type DataGridProps,
  type DataGridColumn,
  type DataGridColumnAlign,
  type DataGridColumnPriority,
  DataGridToolbar,
  type DataGridToolbarProps,
  DataGridSearch,
  type DataGridSearchProps,
  DataGridFilters,
  type DataGridFiltersProps,
  type DataGridFilterDef,
  DataGridBulkActions,
  type DataGridBulkActionsProps,
  useDataGridSelection,
  DataGridSelectionSummary,
  type DataGridSelectionSummaryProps,
  toggleSelection,
  selectAll,
  isAllSelected,
  isPartiallySelected,
  DataGridColumnPicker,
  type DataGridColumnPickerProps,
  type DataGridColumnPickerOption,
  DataGridEmptyState,
  type DataGridEmptyStateProps,
  type DataGridEmptyVariant,
  DataGridLoadingState,
  type DataGridLoadingStateProps,
  DataGridPagination,
  type DataGridPaginationProps,
  InspectorPanel,
  type InspectorPanelProps,
  InspectorHeader,
  type InspectorHeaderProps,
  type InspectorHeaderStatus,
  InspectorSection,
  type InspectorSectionProps,
  InspectorGroup,
  InspectorProperty,
  type InspectorPropertyProps,
  InspectorTabs,
  type InspectorTabsProps,
  InspectorTabPanel,
  type InspectorTabDef,
  InspectorValidation,
  type InspectorValidationProps,
  InspectorStatus,
  type InspectorStatusProps,
  type InspectorStatusItem,
  InspectorHistory,
  type InspectorHistoryProps,
  type InspectorHistoryEntry,
  InspectorActions,
  type InspectorActionsProps,
  InspectorFooter,
  type InspectorFooterProps,
  PropertyPanel,
  type PropertyPanelProps,
  PropertyActions,
  PropertyRow,
  type PropertyRowProps,
  PropertyLabel,
  PropertyValue,
  PropertyReset,
  type PropertyResetProps,
  PropertyToggle,
  type PropertyToggleProps,
  PropertySelect,
  type PropertySelectProps,
  PropertyNumber,
  type PropertyNumberProps,
  PropertyColor,
  type PropertyColorProps,
  PropertyEditor as InspectorPropertyEditor,
  type PropertyEditorField as InspectorPropertyEditorField,
  AssetBrowser,
  type AssetBrowserProps,
  type AssetBrowserPagination,
  AssetBrowserToolbar,
  AssetGrid,
  type AssetGridRenderer,
  type AssetGridProps,
  AssetList,
  type AssetListProps,
  AssetCard,
  type AssetCardProps,
  AssetThumbnail,
  type AssetThumbnailProps,
  AssetMetadata,
  type AssetMetadataProps,
  useAssetSelection,
  AssetSelectionSummary,
  AssetFilters,
  type AssetFilterDef,
  AssetSearch,
  AssetViewToggle,
  type AssetViewToggleProps,
  type AssetViewMode,
  AssetEmptyState,
  type AssetEmptyStateProps,
  type AssetEmptyVariant,
  AssetLoadingState,
  type AssetLoadingStateProps,
  AssetPagination,
  type AssetPaginationProps,
  SearchField,
  SearchScope,
  type SearchScopeProps,
  type SearchScopeOption,
  SearchSuggestions,
  type SearchSuggestionsProps,
  type SearchSuggestion,
  SearchHistory,
  type SearchHistoryProps,
  type SearchHistoryEntry,
  FilterBar as OperationalFilterBar,
  type FilterBarProps as OperationalFilterBarProps,
  FilterGroup,
  type FilterGroupProps,
  type FilterGroupOption,
  FilterChip as OperationalFilterChip,
  type FilterChipProps as OperationalFilterChipProps,
  FilterPopover,
  type FilterPopoverProps,
  FilterSummary,
  type FilterSummaryProps,
  SavedFilter,
  type SavedFilterProps,
  type SavedFilterEntry,
  SortControl,
  type SortControlProps,
  type SortOption,
  ResultSummary,
  type ResultSummaryProps,
  ActiveFilterList,
  type ActiveFilterListProps,
  type ActiveFilterEntry,
  ClearFilters,
  type ClearFiltersProps,
  BulkActionBar,
  type BulkActionBarProps,
  BulkActionGroup,
  type BulkActionGroupProps,
  BulkActionButton,
  type BulkActionButtonProps,
  BulkSelectionSummary,
  BulkSelectionCounter,
  type BulkSelectionCounterProps,
  BulkActionMenu,
  type BulkActionMenuProps,
  type BulkActionMenuItem,
  BulkActionConfirmation,
  type BulkActionConfirmationProps,
  BulkProgress,
  type BulkProgressProps,
  BulkStatus,
  type BulkStatusProps,
  type BulkStatusValue,
  BulkResults,
  type BulkResultsProps,
  BulkUndo,
  type BulkUndoProps,
  BulkConflictList,
  type BulkConflictListProps,
  type BulkConflictEntry,
  StatusPanel,
  type StatusPanelProps,
  HealthPanel,
  type HealthPanelProps,
  HealthScore,
  type HealthScoreProps,
  HealthIndicator,
  type HealthIndicatorProps,
  type HealthStatusValue,
  StatusMetric,
  StatusTimeline,
  type StatusTimelineEntry,
  HealthIssueList,
  type HealthIssueListProps,
  type HealthIssueEntry,
  type HealthIssueSeverity,
  HealthRecommendation,
  type HealthRecommendationProps,
  SyncStatusPanel,
  type SyncStatusPanelProps,
  type SyncSource,
  ProviderHealthPanel,
  type ProviderHealthPanelProps,
  type ProviderHealthRow,
  OperationalAlertPanel,
  type OperationalAlertPanelProps,
  type OperationalAlertEntry,
  Queue,
  type QueueProps,
  QueueHeader,
  type QueueHeaderProps,
  QueueFilters,
  type QueueFiltersProps,
  type QueueFilterValue,
  QueueRow,
  type QueueRowProps,
  type QueueRowJob,
  QueueStatus,
  type QueueStatusProps,
  type QueueStatusValue,
  QueuePriority,
  type QueuePriorityProps,
  type QueuePriorityValue,
  JobCard,
  type JobCardProps,
  JobProgress,
  JobTimeline,
  type JobTimelineProps,
  type JobTimelineEntry,
  JobActions,
  type JobActionsProps,
  JobError,
  type JobErrorProps,
  JobRetry,
  type JobRetryProps,
  JobResults,
  type JobResultsProps,
  QueueEmptyState,
  type QueueEmptyStateProps,
  type QueueEmptyVariant,
  DashboardGrid,
  type DashboardGridProps,
  DashboardSection,
  type DashboardSectionProps,
  MetricCard,
  type MetricCardProps,
  renderMetricTrend,
  type MetricTrendDirection,
  KPIWidget,
  type KPIWidgetProps,
  type KPIWidgetItem,
  TrendWidget,
  type TrendWidgetProps,
  ChartWidget,
  type ChartWidgetProps,
  type ChartWidgetDatum,
  StatusWidget,
  type StatusWidgetProps,
  type StatusWidgetItem,
  ActivityWidget,
  type ActivityWidgetProps,
  QueueWidget,
  type QueueWidgetProps,
  HealthWidget,
  type HealthWidgetProps,
  RecommendationWidget,
  type RecommendationWidgetProps,
  type RecommendationEntry,
  DashboardEmptyState,
  type DashboardEmptyStateProps,
} from "@/components/operational";

// Workflow component family — no collisions with anything above (its own
// selection-helper functions are already aliased internally, e.g.
// `toggleWorkflowSelection`, to avoid clashing with operational's
// DataGrid selection helpers of the same bare names).
export {
  ApprovalActions,
  ApprovalDecision,
  type ApprovalDecisionProps,
  ApprovalFlow,
  ApprovalRequest,
  type ApprovalRequestProps,
  ApprovalStage,
  type ApprovalStateValue,
  ApprovalStatus,
  type ApprovalStatusProps,
  ApprovalStep,
  type ApprovalStepProps,
  DependencyActions,
  type DependencyDirection,
  DependencyEdge,
  type DependencyEdgeProps,
  DependencyFilters,
  type DependencyFiltersProps,
  type DependencyFilterValue,
  DependencyGraph,
  DependencyGroup,
  type DependencyGroupProps,
  DependencyInspector,
  type DependencyInspectorProperty,
  type DependencyInspectorProps,
  DependencyLegend,
  type DependencyLegendProps,
  DependencyNode,
  DependencyNodeMarker,
  type DependencyNodeProps,
  type DependencyStatusValue,
  DependencySummary,
  isAllWorkflowNodesSelected,
  isWorkflowSelectionPartial,
  Pipeline,
  PipelineActions,
  PipelineBranch,
  type PipelineBranchProps,
  PipelineConnector,
  type PipelineConnectorProps,
  PipelineGate,
  type PipelineGateProps,
  PipelineHistory,
  type PipelineHistoryEntry,
  type PipelineHistoryProps,
  PipelineMetrics,
  type PipelineMetricsProps,
  PipelineProgress,
  type PipelineProgressProps,
  PipelineStage,
  PipelineStatus,
  type PipelineStatusProps,
  PipelineStep,
  type PipelineStepProps,
  PipelineSummary,
  RelationshipEdge,
  type RelationshipEdgeProps,
  RelationshipNode,
  RelationshipNodeMarker,
  type RelationshipStatusValue,
  RelationshipView,
  ReviewChecklist,
  type ReviewChecklistItem,
  type ReviewChecklistProps,
  ReviewComment,
  type ReviewCommentProps,
  ReviewHistory,
  type ReviewHistoryEntry,
  type ReviewHistoryProps,
  ReviewPanel,
  type ReviewPanelProps,
  ReviewSummary,
  selectAllWorkflowNodes,
  StateAction,
  type StateActionProps,
  StateActions,
  type StateActionTrigger,
  StateCondition,
  type StateConditionProps,
  type StateEventEntry,
  StateEvents,
  type StateEventsProps,
  StateHistory,
  type StateHistoryEntry,
  type StateHistoryProps,
  StateInspector,
  type StateInspectorProperty,
  type StateInspectorProps,
  StateLegend,
  type StateLegendProps,
  StateMachine,
  StateMetrics,
  type StateMetricsProps,
  StateNode,
  StateNodeMarker,
  type StateNodeProps,
  StateSummary,
  StateTransition,
  type StateTransitionProps,
  type StateValue,
  toggleWorkflowSelection,
  useWorkflowSelection,
  Workflow,
  WorkflowActions,
  WorkflowCanvas,
  WorkflowControls,
  type WorkflowControlsProps,
  WorkflowEdge,
  type WorkflowEdgeDirection,
  WorkflowFooter,
  WorkflowGroup,
  WorkflowHeader,
  type WorkflowHeaderProps,
  WorkflowInspector,
  type WorkflowInspectorProperty,
  type WorkflowInspectorProps,
  WorkflowLegend,
  type WorkflowLegendProps,
  WorkflowMiniMap,
  type WorkflowMiniMapNode,
  type WorkflowMiniMapProps,
  WorkflowNode,
  WorkflowNodeMarker,
  type WorkflowNodeProps,
  type WorkflowNodeStatus,
  WorkflowOverview,
  type WorkflowOverviewProps,
  WorkflowProgress,
  type WorkflowProgressProps,
  type WorkflowProps,
  WorkflowSelection,
  WorkflowSidebar,
  type WorkflowSidebarProps,
  WorkflowStage,
  WorkflowStageGroup,
  type WorkflowStageGroupProps,
  type WorkflowStageProps,
  type WorkflowStateValue,
  WorkflowStatus,
  type WorkflowStatusProps,
  WorkflowStep,
  WorkflowStepper,
  WorkflowStepperActions,
  WorkflowStepperConnector,
  type WorkflowStepperConnectorProps,
  WorkflowStepperFooter,
  WorkflowStepperHeader,
  WorkflowStepperNavigation,
  type WorkflowStepperNavigationProps,
  WorkflowStepperProgress,
  type WorkflowStepperProgressProps,
  WorkflowStepperStage,
  type WorkflowStepperStateValue,
  WorkflowStepperStep,
  type WorkflowStepperStepProps,
  WorkflowStepperSummary,
  type WorkflowStepProps,
  WorkflowSummary,
  type WorkflowSummaryProps,
  WorkflowTimeline,
  WorkflowTimelineConnector,
  type WorkflowTimelineConnectorProps,
  WorkflowTimelineEvent,
  type WorkflowTimelineEventProps,
  type WorkflowTimelineEventStatus,
  WorkflowTimelineFilters,
  type WorkflowTimelineFiltersProps,
  type WorkflowTimelineFilterValue,
  WorkflowTimelineFooter,
  WorkflowTimelineGroup,
  type WorkflowTimelineGroupProps,
  WorkflowTimelineHeader,
  WorkflowTimelineLegend,
  type WorkflowTimelineLegendProps,
  WorkflowTimelineMarker,
  type WorkflowTimelineMarkerProps,
  WorkflowTimelineSummary,
  WorkflowToolbar,
  type WorkflowToolbarProps,
  WorkflowTransition,
  type WorkflowTransitionProps,
  type WorkflowTransitionStatus,
  WorkflowViewport,
  type WorkflowViewportProps,
} from "@/components/workflow";

// Hooks
export {
  type EditSessionActions,
  type EditSessionCommitResult,
  type EditSessionResult,
  type EditSessionStatus,
  useAnimationSpeed,
  useBodyLock,
  useEditSession,
  type UseEditSessionOptions,
  useEscapeKey,
  useFocusTrap,
  useMotion,
  useMotionControls,
  useMotionEnabled,
  useOutsideClick,
  useReducedMotion,
} from "@/hooks";

// Providers
export {
  MotionContext,
  type MotionContextValue,
  type MotionDiagnostics,
  MotionProvider,
  type PlaybackSpeed,
} from "@/providers";

// Shared utility
export { cn } from "@/lib/utils";
