/**
 * @studiopod/design/marketing — the 11 canonical marketing
 * composition components (Hero, CTA, FeatureGrid, Comparison, Metrics,
 * Timeline, FAQ, Testimonial, Empty, Workflow, Platform).
 */
// Named explicitly (DH-5): a composition added to @/compositions now joins the
// public API only when someone decides it should.
export {
  type ComparisonCard,
  ComparisonComposition,
  type ComparisonCompositionProps,
  type ComparisonPoint,
  type ComparisonVariant,
  CTAComposition,
  type CTACompositionProps,
  type CTALayout,
  type CTASize,
  EmptyComposition,
  type EmptyCompositionProps,
  type EmptyVariant,
  FAQComposition,
  type FAQCompositionProps,
  type FAQItem,
  FeatureGridComposition,
  type FeatureGridCompositionProps,
  type FeatureGridItem,
  HeroComposition,
  type HeroCompositionProps,
  type HeroLayout,
  type HeroMetric,
  type HeroTrustRow,
  type MatrixColumn,
  type MatrixRow,
  type MetricItem,
  MetricsComposition,
  type MetricsCompositionProps,
  type MetricsVariant,
  type MetricTrend,
  PlatformComposition,
  type PlatformCompositionProps,
  type PlatformNode,
  type Testimonial,
  TestimonialComposition,
  type TestimonialCompositionProps,
  type TestimonialLayout,
  TimelineComposition,
  type TimelineCompositionProps,
  type TimelineItem,
  type TimelineOrientation,
  WorkflowComposition,
  type WorkflowCompositionProps,
  type WorkflowStep,
} from "@/compositions";
