export interface OperationsImplementationGuidance {
  label: string;
  text: string;
}

export const IMPLEMENTATION_GUIDANCE: OperationsImplementationGuidance[] = [
  { label: "Platform composition", text: "Every one of these 12 components is a pure re-export over an already-certified Workflow or Operational component — checked directly against Platform Rules (defined in DS-4.1) before writing each file, and in every case an existing component's prop surface already covered the need with no Operations-specific field required. OperationsAlerts (= OperationalAlertPanel) and OperationsMonitoring (= ProviderHealthPanel) are this package's first real Platform-tier consumers of those two Operational components." },
  { label: "Workflow integration", text: "OperationsAutomation composes Pipeline Components' own PipelineStage directly for automated step-by-step progression, the same shape CommerceFulfillment and ProductionStagePanel already established. OperationsInspector composes State Machine directly for a single item's own lifecycle." },
  { label: "Operational integration", text: "OperationsMonitoring composes Status & Health System's own ProviderHealthPanel directly — reused here for generic multi-system monitoring (name/status/latency/uptime), not literally about external providers, the same kind of domain-generalized reuse Publishing Platform's own PublishingProviders already established. OperationsScheduler composes Operational's own Queue directly, the same reuse target Production/Publishing Platform's own job-queue components already chose. OperationsHealth composes Status & Health's own HealthPanel directly. OperationsAlerts composes Status & Health's own OperationalAlertPanel directly." },
  { label: "Monitoring presentation", text: "OperationsMonitoring does not implement real polling, heartbeat, or uptime-check logic — it renders whatever ProviderHealthRow[] the caller supplies through ProviderHealthPanel. Whether a system is actually being monitored is Business Feature logic, not something this platform component decides." },
  { label: "Automation workflows", text: "OperationsAutomation does not implement a real job scheduler or workflow-execution engine — its own children slot is where WorkflowStep content belongs for each automated stage, the same composition pattern ProductionStagePanel's own gallery already established." },
  { label: "Alert presentation", text: "OperationsAlerts does not implement alert-triggering-condition evaluation or notification delivery (email/push/webhook) — it renders whatever OperationalAlertEntry[] the caller supplies through OperationalAlertPanel. Which conditions actually fire an alert is Business Feature logic." },
  { label: "Health organization", text: "OperationsHealth does not implement real health-check or scoring logic — it renders whatever score/metrics/issues/recommendations the caller supplies through HealthPanel, the same reuse Intelligence Platform's own IntelligenceHealth already established." },
];
