import { INVENTORY_GROUPS, type InventoryStatus, type InventoryPriority } from "../../inventory/_data/inventory";
import { MATURITY_FROM_STATUS, type MaturityLevel } from "../../_data/maturity";

export type FoundationGroupId =
  | "actions"
  | "inputs"
  | "feedback"
  | "overlays"
  | "navigation"
  | "data-display"
  | "layout-primitives";

export interface FoundationGroupDef {
  id: FoundationGroupId;
  title: string;
  description: string;
}

export const FOUNDATION_GROUPS: FoundationGroupDef[] = [
  { id: "actions", title: "Actions", description: "Buttons and other triggers a user clicks to do something." },
  { id: "inputs", title: "Inputs", description: "Form controls for entering or selecting a value." },
  { id: "feedback", title: "Feedback", description: "Communicating state, status, and outcome back to the user." },
  { id: "overlays", title: "Overlays", description: "Content that floats above the page on demand, dismissed explicitly." },
  { id: "navigation", title: "Navigation", description: "Moving between views, pages, sections, or steps." },
  { id: "data-display", title: "Data Display", description: "Presenting structured content and information at rest." },
  { id: "layout-primitives", title: "Layout Primitives", description: "The composition building blocks every other component is arranged with." },
];

export interface FoundationComponent {
  id: string;
  name: string;
  groupId: FoundationGroupId;
  purpose: string;
  status: InventoryStatus;
  source?: string;
  requiredStates: string[];
  requiredVariants: string[];
  accessibility: string[];
  reuseTargets: string[];
  priority: InventoryPriority;
  /** Set only when this entry's status/source/priority was looked up from the DS-0.2 inventory rather than derived fresh from the codebase. */
  derivedFrom?: string;
}

const ALL_INVENTORY_ITEMS = INVENTORY_GROUPS.flatMap((group) => group.items);

function fromInventory(name: string) {
  const item = ALL_INVENTORY_ITEMS.find((i) => i.name === name);
  if (!item) throw new Error(`Foundation catalog references unknown inventory item: ${name}`);
  return item;
}

const INTERACTIVE_STATES = ["Default", "Hover", "Focus", "Active", "Disabled"];
const FIELD_STATES = ["Default", "Focus", "Disabled", "Error", "Success"];
const FIELD_A11Y = ["Associated <label>", "aria-invalid on error", "aria-describedby for helper/error text", "Full keyboard operability"];

export const FOUNDATION_COMPONENTS: FoundationComponent[] = [
  // Actions
  {
    id: "button",
    name: "Button",
    groupId: "actions",
    purpose: "The primary trigger for a user-initiated action.",
    status: "Exists",
    source: "src/components/ui/Button.tsx",
    priority: "Low",
    requiredStates: [...INTERACTIVE_STATES, "Loading"],
    requiredVariants: ["Primary", "Secondary", "Ghost", "Destructive", "sm/md/lg"],
    accessibility: ["Native <button> or <a> semantics", "Focus ring", "aria-busy while loading", "Disabled blocks activation, not just styling"],
    reuseTargets: ["Every Workspace Toolbar action", "Every Dialog's confirm/cancel pair"],
  },
  {
    id: "icon-button",
    name: "Icon Button",
    groupId: "actions",
    purpose: "A square, icon-only trigger for a single unambiguous action in dense chrome.",
    status: "Partial",
    source: "src/components/ui/Button.tsx (supports a leading icon with empty label, but no dedicated square icon-only mode or enforced aria-label)",
    priority: "High",
    requiredStates: INTERACTIVE_STATES,
    requiredVariants: ["sm/md/lg", "Ghost", "Toggled/pressed"],
    accessibility: ["Required aria-label (no visible text to label it)", "Tooltip on hover/focus for sighted users"],
    reuseTargets: ["Workspace Toolbar dense actions", "Asset Card row actions"],
  },
  {
    id: "button-group",
    name: "Button Group",
    groupId: "actions",
    purpose: "A visually connected row of related buttons, acting as one control.",
    status: "Needed",
    source: "src/components/ui/CTAGroup.tsx (a related row-of-buttons shape, built for marketing CTA spacing, not a connected/segmented group)",
    priority: "Medium",
    requiredStates: INTERACTIVE_STATES,
    requiredVariants: ["Horizontal", "Connected borders", "With dividers"],
    accessibility: ["role=\"group\" with an accessible label"],
    reuseTargets: ["Workspace Toolbar view toggles"],
  },
  {
    id: "dropdown-button",
    name: "Dropdown Button",
    groupId: "actions",
    purpose: "A button that opens a Menu of related actions instead of triggering one directly.",
    status: "Needed",
    source: "No Menu primitive exists yet to build this on — see Menu below.",
    priority: "Medium",
    requiredStates: [...INTERACTIVE_STATES, "Open"],
    requiredVariants: ["Primary", "Secondary", "Ghost"],
    accessibility: ["aria-haspopup=\"menu\"", "aria-expanded", "Arrow-key navigation once open"],
    reuseTargets: ["Batch Action Bar", "Queue Table row actions"],
  },
  {
    id: "split-button",
    name: "Split Button",
    groupId: "actions",
    purpose: "A primary action button paired with an adjoining Dropdown Button for related alternatives.",
    status: "Needed",
    source: "Depends on both Button Group and Dropdown Button, neither of which exist yet.",
    priority: "Low",
    requiredStates: [...INTERACTIVE_STATES, "Open"],
    requiredVariants: ["Primary", "Secondary"],
    accessibility: ["Two independently focusable, independently labeled controls"],
    reuseTargets: ["Publishing Operations primary publish action with channel alternatives"],
  },

  // Inputs
  {
    id: "input",
    name: "Input",
    groupId: "inputs",
    purpose: fromInventory("Input").purpose,
    status: fromInventory("Input").status,
    source: fromInventory("Input").source,
    priority: fromInventory("Input").priority,
    derivedFrom: "DS-0.2 inventory: Input",
    requiredStates: FIELD_STATES,
    requiredVariants: ["Text", "Number", "Password", "With leading/trailing icon"],
    accessibility: FIELD_A11Y,
    reuseTargets: ["Every form field across every DS-2.x operational component"],
  },
  {
    id: "textarea",
    name: "Textarea",
    groupId: "inputs",
    purpose: fromInventory("Textarea").purpose,
    status: fromInventory("Textarea").status,
    source: fromInventory("Textarea").source,
    priority: fromInventory("Textarea").priority,
    derivedFrom: "DS-0.2 inventory: Textarea",
    requiredStates: FIELD_STATES,
    requiredVariants: ["Fixed rows", "Auto-growing"],
    accessibility: FIELD_A11Y,
    reuseTargets: ["Property Editor long-text fields"],
  },
  {
    id: "select",
    name: "Select",
    groupId: "inputs",
    purpose: fromInventory("Select").purpose,
    status: fromInventory("Select").status,
    source: fromInventory("Select").source,
    priority: fromInventory("Select").priority,
    derivedFrom: "DS-0.2 inventory: Select",
    requiredStates: FIELD_STATES,
    requiredVariants: ["Single-select", "Placeholder option"],
    accessibility: FIELD_A11Y,
    reuseTargets: ["Property Editor enum fields"],
  },
  {
    id: "combobox",
    name: "Combobox",
    groupId: "inputs",
    purpose: fromInventory("Combobox").purpose,
    status: "Exists",
    source: "src/components/form/ComboboxField.tsx — built in DS-2.1.5: real typeahead filtering, Arrow/Enter/Escape keyboard support, and the ARIA combobox pattern (role=\"combobox\" + role=\"listbox\").",
    priority: fromInventory("Combobox").priority,
    derivedFrom: "DS-0.2 inventory: Combobox",
    requiredStates: [...FIELD_STATES, "Loading options", "No results"],
    requiredVariants: ["Single-select", "Multi-select", "Async-loaded options"],
    accessibility: [...FIELD_A11Y, "ARIA combobox pattern (listbox + active-descendant)"],
    reuseTargets: ["Provider/capability pickers", "Structured Property Editor fields"],
  },
  {
    id: "checkbox",
    name: "Checkbox",
    groupId: "inputs",
    purpose: fromInventory("Checkbox").purpose,
    status: fromInventory("Checkbox").status,
    source: fromInventory("Checkbox").source,
    priority: fromInventory("Checkbox").priority,
    derivedFrom: "DS-0.2 inventory: Checkbox",
    requiredStates: [...INTERACTIVE_STATES, "Checked", "Indeterminate"],
    requiredVariants: ["Standalone", "With label"],
    accessibility: ["Native checkbox semantics", "Indeterminate set via DOM property, not an attribute"],
    reuseTargets: ["Asset Workspace row/grid multi-select"],
  },
  {
    id: "radio",
    name: "Radio",
    groupId: "inputs",
    purpose: "A single option within a mutually exclusive group.",
    status: "Exists",
    source: "src/components/ui/RadioGroup.tsx (ships as a group, not a standalone single Radio — the common real-world usage)",
    priority: "Low",
    requiredStates: [...INTERACTIVE_STATES, "Checked"],
    requiredVariants: ["Standalone option", "Full group"],
    accessibility: ["role=\"radiogroup\" on the container", "Arrow-key navigation between options"],
    reuseTargets: ["Property Editor mutually-exclusive fields"],
  },
  {
    id: "switch",
    name: "Switch",
    groupId: "inputs",
    purpose: fromInventory("Switch").purpose,
    status: fromInventory("Switch").status,
    source: fromInventory("Switch").source,
    priority: fromInventory("Switch").priority,
    derivedFrom: "DS-0.2 inventory: Switch",
    requiredStates: [...INTERACTIVE_STATES, "Checked"],
    requiredVariants: ["Standalone", "With label"],
    accessibility: ["role=\"switch\" with aria-checked"],
    reuseTargets: ["Property Editor boolean fields", "Feature-flag toggles"],
  },
  {
    id: "slider",
    name: "Slider",
    groupId: "inputs",
    purpose: "Dragging or keying to a numeric value within a range.",
    status: "Exists",
    source: "src/components/ui/Slider.tsx",
    priority: "Low",
    requiredStates: [...INTERACTIVE_STATES, "Dragging"],
    requiredVariants: ["Single thumb", "With value label"],
    accessibility: ["role=\"slider\" with aria-valuemin/max/now", "Arrow-key increment/decrement"],
    reuseTargets: ["Numeric Property Editor fields with a bounded range"],
  },
  {
    id: "date-picker",
    name: "Date Picker",
    groupId: "inputs",
    purpose: "Selecting a calendar date, and optionally a range, through a structured picker rather than free text.",
    status: "Exists",
    source: "src/components/form/DatePickerField.tsx — built in DS-2.1.5 on a native <input type=\"date\">, giving real keyboard grid navigation from the browser itself rather than a custom-built popover. Date range remains a gap.",
    priority: "Medium",
    requiredStates: [...FIELD_STATES, "Open"],
    requiredVariants: ["Single date", "Date range"],
    accessibility: ["Full keyboard grid navigation", "Announces the selected date on change"],
    reuseTargets: ["Publishing schedule fields", "Activity Timeline date filters"],
  },
  {
    id: "file-upload",
    name: "File Upload",
    groupId: "inputs",
    purpose: "Selecting or dragging in one or more files to attach or import.",
    status: "Exists",
    source: "src/components/form/FileUploadField.tsx — built in DS-2.1.5: a drag-and-drop zone wrapping a real, always-present native file input, with a removable file list.",
    priority: "Medium",
    requiredStates: ["Default", "Drag-over", "Uploading", "Error", "Disabled"],
    requiredVariants: ["Single file", "Multi-file", "Drop zone"],
    accessibility: ["Native file input fallback always present, never drag-only"],
    reuseTargets: ["Assets Workspace import", "Provider credential upload"],
  },

  // Feedback
  {
    id: "badge",
    name: "Badge",
    groupId: "feedback",
    purpose: "A small, static label communicating a category or status at a glance.",
    status: "Exists",
    source: "src/components/ui/Badge.tsx",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["neutral", "accent", "success", "warning", "error", "sm/md"],
    accessibility: ["Text conveys meaning, not color alone"],
    reuseTargets: ["Used throughout every DS-1.x page already — the most reused foundation component in the system"],
  },
  {
    id: "chip",
    name: "Chip",
    groupId: "feedback",
    purpose: "A compact, often dismissible token representing one applied filter or selection.",
    status: "Needed",
    source: "src/components/ui/FilterBar.tsx (defines a FilterChip data shape and renders it inline — no standalone, reusable Chip component)",
    priority: "Medium",
    requiredStates: [...INTERACTIVE_STATES, "Selected"],
    requiredVariants: ["Static", "Dismissible (with an ×)"],
    accessibility: ["Dismiss control has its own accessible label"],
    reuseTargets: ["Filter Bar active filters"],
  },
  {
    id: "tag",
    name: "Tag",
    groupId: "feedback",
    purpose: "A user- or system-assigned label attached to an item, distinct from a status Badge.",
    status: "Needed",
    source: "src/components/ui/Badge.tsx (the closest visual primitive, but Badge's tone system is status-oriented, not built for arbitrary user labels)",
    priority: "Low",
    requiredStates: ["Default", "Removable"],
    requiredVariants: ["Static", "Removable"],
    accessibility: ["Remove control has its own accessible label"],
    reuseTargets: ["Asset metadata tagging"],
  },
  {
    id: "toast",
    name: "Toast",
    groupId: "feedback",
    purpose: "A brief, self-dismissing notification for something that just happened.",
    status: "Needed",
    priority: "High",
    requiredStates: ["Entering", "Visible", "Exiting", "Paused on hover"],
    requiredVariants: ["Success", "Error", "Info", "With action"],
    accessibility: ["ARIA live region, polite by default", "Pauses auto-dismiss on hover/focus"],
    reuseTargets: ["Operational Status Notifications region"],
  },
  {
    id: "alert",
    name: "Alert",
    groupId: "feedback",
    purpose: "A full-width inline banner for page- or section-level warnings and errors.",
    status: fromInventory("Warning Banner").status,
    source: fromInventory("Warning Banner").source,
    priority: fromInventory("Warning Banner").priority,
    derivedFrom: "DS-0.2 inventory: Warning Banner",
    requiredStates: ["Default", "Dismissible"],
    requiredVariants: ["Info", "Success", "Warning", "Error"],
    accessibility: ["role=\"alert\" for errors, role=\"status\" for info/success"],
    reuseTargets: ["Operational Status page-level warnings", "Validation Panel summary"],
  },
  {
    id: "progress",
    name: "Progress",
    groupId: "feedback",
    purpose: "An animated fill bar communicating completion of a task with a knowable duration.",
    status: fromInventory("Progress Indicator").status,
    source: fromInventory("Progress Indicator").source,
    priority: fromInventory("Progress Indicator").priority,
    derivedFrom: "DS-0.2 inventory: Progress Indicator",
    requiredStates: ["Determinate", "Indeterminate", "Complete", "Error"],
    requiredVariants: ["Linear", "With percentage label"],
    accessibility: ["role=\"progressbar\" with aria-valuenow/min/max"],
    reuseTargets: ["Background Jobs progress fills"],
  },
  {
    id: "spinner",
    name: "Spinner",
    groupId: "feedback",
    purpose: "An indeterminate loading indicator for content or an action with no knowable duration.",
    status: "Partial",
    source: "src/components/ui/Button.tsx and SearchInput.tsx (both render a Loader2 icon inline for their own loading state — no standalone, reusable Spinner)",
    priority: "Medium",
    requiredStates: ["Visible"],
    requiredVariants: ["sm/md/lg", "Inline", "Full-region overlay"],
    accessibility: ["aria-hidden with an accompanying text label elsewhere (a spinner alone announces nothing useful)"],
    reuseTargets: ["Any async region without a knowable duration"],
  },
  {
    id: "skeleton",
    name: "Skeleton",
    groupId: "feedback",
    purpose: "A placeholder shape approximating content that hasn't loaded yet.",
    status: "Exists",
    source: "src/components/ui/Skeleton.tsx",
    priority: "Low",
    requiredStates: ["Loading"],
    requiredVariants: ["Text line", "Block", "Circle (avatar)"],
    accessibility: ["aria-hidden — the loading state itself is announced elsewhere, not per-skeleton"],
    reuseTargets: ["Library Grid loading state"],
  },
  {
    id: "empty-state",
    name: "Empty State",
    groupId: "feedback",
    purpose: "A dedicated placeholder for a region with nothing to show — no data, no results, or a failed load.",
    status: fromInventory("Error State").status,
    source: fromInventory("Error State").source,
    priority: fromInventory("Error State").priority,
    derivedFrom: "DS-0.2 inventory: Error State",
    requiredStates: ["No data", "No results", "Error"],
    requiredVariants: ["With illustration", "With retry action"],
    accessibility: ["Announced when it replaces previously-visible content"],
    reuseTargets: ["Library Grid/Table empty states", "Diagnostics Panel no-issues state"],
  },

  // Overlays
  {
    id: "dialog",
    name: "Dialog",
    groupId: "overlays",
    purpose: "A focused, modal surface that blocks the rest of the page until dismissed.",
    status: "Needed",
    priority: "High",
    requiredStates: ["Entering", "Open", "Exiting"],
    requiredVariants: ["Confirmation", "Form", "Full content"],
    accessibility: ["Focus trapped inside while open", "Focus returns to the trigger on close", "Escape closes it", "role=\"dialog\" with aria-modal"],
    reuseTargets: ["Destructive confirmations across every DS-2.x package"],
  },
  {
    id: "drawer",
    name: "Drawer",
    groupId: "overlays",
    purpose: "A panel that slides in from an edge without fully blocking the page behind it.",
    status: "Needed",
    priority: "High",
    requiredStates: ["Entering", "Open", "Exiting"],
    requiredVariants: ["Right edge", "Bottom edge"],
    accessibility: ["Focus trapped while open", "Escape closes it"],
    reuseTargets: ["Inspector Workspace's Drawer responsive mode", "Operational Status's Drawer responsive mode"],
  },
  {
    id: "popover",
    name: "Popover",
    groupId: "overlays",
    purpose: "A small, anchored surface of contextual content or controls, dismissed on outside click.",
    status: "Needed",
    priority: "Medium",
    requiredStates: ["Open", "Closed"],
    requiredVariants: ["Anchored to a trigger element"],
    accessibility: ["Dismissed by Escape and outside click", "Focus returns to the trigger on close"],
    reuseTargets: ["Quick health detail from Operational Health"],
  },
  {
    id: "menu",
    name: "Menu",
    groupId: "overlays",
    purpose: "A list of actions or options anchored to a trigger, dismissed on selection or outside click.",
    status: "Needed",
    priority: "High",
    requiredStates: ["Open", "Closed", "Item highlighted"],
    requiredVariants: ["Action list", "With icons", "With destructive items separated"],
    accessibility: ["ARIA menu pattern", "Arrow-key navigation", "Type-ahead"],
    reuseTargets: ["Dropdown Button", "Queue Table and Asset Card row actions"],
  },
  {
    id: "tooltip",
    name: "Tooltip",
    groupId: "overlays",
    purpose: "A brief label revealed on hover or focus, clarifying an otherwise unlabeled control.",
    status: "Needed",
    priority: "High",
    requiredStates: ["Hidden", "Visible"],
    requiredVariants: ["Text only"],
    accessibility: ["Triggered by focus as well as hover — never hover-only", "Dismissed by Escape"],
    reuseTargets: ["Icon Button labels", "Truncated text throughout the catalog"],
  },
  {
    id: "command-palette",
    name: "Command Palette",
    groupId: "overlays",
    purpose: "A searchable, keyboard-first overlay for jumping to an action or destination without the mouse.",
    status: "Needed",
    priority: "Low",
    requiredStates: ["Open", "Closed", "Searching", "No results"],
    requiredVariants: ["Actions", "Navigation destinations"],
    accessibility: ["ARIA combobox/listbox pattern", "Global keyboard shortcut to open"],
    reuseTargets: ["Future Workflow Assistant / AI Operations Center extensions"],
  },

  // Navigation
  {
    id: "tabs",
    name: "Tabs",
    groupId: "navigation",
    purpose: "Switching between several views that share the same context without navigating away.",
    status: "Partial",
    source: "src/components/ui/SegmentedControl.tsx (the same row-of-buttons-with-one-active pattern, but built as a choice input, not a tabpanel/tab-role navigation component)",
    priority: "High",
    requiredStates: ["Selected", "Unselected", "Disabled"],
    requiredVariants: ["Horizontal", "With counts/badges per tab"],
    accessibility: ["ARIA tabs pattern (tablist/tab/tabpanel)", "Arrow-key navigation between tabs"],
    reuseTargets: ["Inspector Workspace region switching"],
  },
  {
    id: "breadcrumbs",
    name: "Breadcrumbs",
    groupId: "navigation",
    purpose: fromInventory("Breadcrumbs").purpose,
    status: fromInventory("Breadcrumbs").status,
    source: fromInventory("Breadcrumbs").source,
    priority: fromInventory("Breadcrumbs").priority,
    derivedFrom: "DS-0.2 inventory: Breadcrumbs",
    requiredStates: ["Default"],
    requiredVariants: ["With truncation for deep hierarchies"],
    accessibility: ["nav landmark with an accessible label", "aria-current=\"page\" on the last crumb"],
    reuseTargets: ["Workspace Header context region"],
  },
  {
    id: "pagination",
    name: "Pagination",
    groupId: "navigation",
    purpose: "Moving through a large result set page by page.",
    status: "Needed",
    priority: "Medium",
    requiredStates: ["Default", "Current page", "Disabled (first/last)"],
    requiredVariants: ["Numbered", "Prev/next only", "Load more"],
    accessibility: ["nav landmark", "aria-current=\"page\" on the active page"],
    reuseTargets: ["Library Table long result sets"],
  },
  {
    id: "stepper",
    name: "Stepper",
    groupId: "navigation",
    purpose: "Showing progress through a fixed, ordered sequence of steps.",
    status: "Needed",
    source: "src/compositions/TimelineComposition.tsx and the Production package's gate diagrams (the ordered-steps visual pattern exists as a diagram, not an interactive UI stepper)",
    priority: "Medium",
    requiredStates: ["Upcoming", "Current", "Complete", "Error"],
    requiredVariants: ["Horizontal", "Vertical", "Numbered", "With labels"],
    accessibility: ["Current step announced", "aria-current=\"step\""],
    reuseTargets: ["Approval Panel multi-stage review", "Publishing Operations pipeline stages"],
  },
  {
    id: "sidebar-nav",
    name: "Sidebar Nav",
    groupId: "navigation",
    purpose: "The primary sidebar for moving between an app's top-level sections.",
    status: fromInventory("Workspace Navigation").status,
    source: fromInventory("Workspace Navigation").source,
    priority: fromInventory("Workspace Navigation").priority,
    derivedFrom: "DS-0.2 inventory: Workspace Navigation",
    requiredStates: ["Default", "Active section", "Collapsed (icon-only)"],
    requiredVariants: ["Expanded", "Collapsed", "With section grouping"],
    accessibility: ["nav landmark with an accessible label", "aria-current=\"page\" on the active item"],
    reuseTargets: ["Workspace Shell's own Navigation region"],
  },
  {
    id: "section-nav",
    name: "Section Nav",
    groupId: "navigation",
    purpose: "An in-page anchor nav that highlights the section currently in view while scrolling.",
    status: "Partial",
    source: "src/app/design-system/_components/PlaygroundNav.tsx (a working scroll-spy nav, built page-scoped for one playground rather than generalized as a reusable component)",
    priority: "Low",
    requiredStates: ["Default", "Active (in view)"],
    requiredVariants: ["Vertical rail", "Horizontal scroll-spy bar"],
    accessibility: ["aria-current=\"true\" on the in-view section link"],
    reuseTargets: ["Long documentation pages like this catalog itself"],
  },

  // Data Display
  {
    id: "card",
    name: "Card",
    groupId: "data-display",
    purpose: "A bounded surface grouping related content, the base unit nearly everything else is composed from.",
    status: "Exists",
    source: "src/components/ui/Card.tsx",
    priority: "Low",
    requiredStates: ["Default", "Interactive (hover/focus)"],
    requiredVariants: ["sm/md/lg padding", "Interactive/static"],
    accessibility: ["Interactive cards use a real button/link semantic, never a bare clickable div alone"],
    reuseTargets: ["Used throughout every DS-0.3/DS-1.x page already"],
  },
  {
    id: "table",
    name: "Table",
    groupId: "data-display",
    purpose: "Structured, sortable rows and columns of data.",
    status: "Exists",
    source: "src/components/table/ — built in DS-2.1.3 as a 13-component system (Table, TableHeader/Body/Footer/Row/Cell/Head, TableSelectionCell, TableStatusCell, TableActionCell, TableEmptyState, TableLoadingState, TableToolbar), plus src/components/table/ResponsiveRulesTable.tsx added in DS-2.1.7.2, which required extending TableHead with a sticky prop for a pinned left column. Adopted by 3 real pages (workspace-layout, workspace-toolbar, primary-workspace) in DS-2.1.7.2, replacing 3 duplicate implementations. DS-2.1.7.3 (MaturityTable) and DS-2.1.7.4 (InventoryTable) were both attempted next and both reverted: migrating either onto Table produced a measured mobile regression (640px and 774px natural width against a 333px viewport, respectively) because Table has no responsive row-collapse capability — confirmed twice, independently. Status: Adoption In Progress, not Certified. Remaining hand-rolled tables (CoverageMatrix, ScorecardTable, CertificationMatrix) have not been migrated yet; MaturityTable and InventoryTable are both blocked on the row-collapse gap, not just unattempted.",
    priority: "High",
    requiredStates: ["Default row", "Selected row", "Loading", "Empty"],
    requiredVariants: ["Sortable columns", "Sticky first column", "Row selection", "Responsive row collapse (confirmed gap — DS-2.1.7.3)"],
    accessibility: ["Native <table> with scope on header cells", "Sort state announced"],
    reuseTargets: ["Queue Table", "Library Table", "Coverage Matrix, Scorecard, and Certification Matrix's own hand-rolled tables, once generalized"],
  },
  {
    id: "list",
    name: "List",
    groupId: "data-display",
    purpose: "A vertical sequence of related items, each with a consistent internal layout.",
    status: "Needed",
    source: "Hand-rolled <ul>/<li> rows recur across nearly every DS-1.x principles/checklist section — never generalized into one component.",
    priority: "Medium",
    requiredStates: ["Default item", "Selected item", "Empty"],
    requiredVariants: ["Simple", "With leading icon/avatar", "Divided"],
    accessibility: ["Native list semantics (ul/li)"],
    reuseTargets: ["Recommendation Card lists", "Activity Timeline entries"],
  },
  {
    id: "description-list",
    name: "Description List",
    groupId: "data-display",
    purpose: "A set of label/value pairs, presented as rows.",
    status: "Exists",
    source: "src/components/layout/DescriptionList.tsx — built in DS-2.1.2, generalizing the dl/dt/dd row pattern that had been hand-rolled identically across every DS-1.x Accessibility section since DS-1.2. Also documented as a Foundation Metadata component (src/components/metadata/DescriptionList.tsx re-exports it). Adopted by all 9 real duplicate implementations in DS-2.1.7.1 — the Foundation Layer's first production adoption. Status: Adoption In Progress, not Certified.",
    priority: "High",
    requiredStates: ["Default row"],
    requiredVariants: ["Stacked (mobile)", "Side-by-side (desktop)"],
    accessibility: ["Native dl/dt/dd semantics"],
    reuseTargets: ["Every DS-1.x page's Accessibility section", "Property Editor read-only fields"],
  },
  {
    id: "stat",
    name: "Stat",
    groupId: "data-display",
    purpose: "A single labeled metric, sized for a dashboard or summary row.",
    status: "Exists",
    source: "src/components/ui/StatCard.tsx",
    priority: "Low",
    requiredStates: ["Default", "With trend indicator"],
    requiredVariants: ["Compact", "With icon"],
    accessibility: ["Value and label both in the accessible name — a number alone announces nothing"],
    reuseTargets: ["Metrics Card", "Catalog Summary counts"],
  },
  {
    id: "avatar",
    name: "Avatar",
    groupId: "data-display",
    purpose: "A compact visual representation of a person, team, or provider.",
    status: "Needed",
    priority: "Medium",
    requiredStates: ["Image loaded", "Fallback initials", "Fallback icon"],
    requiredVariants: ["sm/md/lg", "Single", "Stacked group"],
    accessibility: ["Accessible name via alt text or aria-label, never image-only with no name"],
    reuseTargets: ["Live Team Presence future extension", "Job Status Card triggered-by"],
  },
  {
    id: "icon",
    name: "Icon",
    groupId: "data-display",
    purpose: "A single glyph from the design system's icon set, sized and colored consistently.",
    status: "Partial",
    source: "lucide-react icons are imported and sized directly wherever needed (e.g. size-3.5, size-4) — consistent by convention, not enforced by a wrapping Icon component or token-driven size scale.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["xs/sm/md/lg sizes tied to spacing tokens"],
    accessibility: ["aria-hidden by default; accessible name only when the icon is the sole content of a control"],
    reuseTargets: ["Every component in this catalog that renders an icon"],
  },
  {
    id: "divider",
    name: "Divider",
    groupId: "data-display",
    purpose: "A thin visual line separating content within a single region.",
    status: "Needed",
    source: "border-t/border-b border-border-subtle utility classes are applied ad hoc wherever a divider is needed, rather than through one component.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["Horizontal", "Vertical"],
    accessibility: ["aria-hidden — purely visual"],
    reuseTargets: ["Card internal section breaks throughout the catalog"],
  },

  // Layout Primitives
  {
    id: "stack",
    name: "Stack",
    groupId: "layout-primitives",
    purpose: "A vertical flex arrangement with consistent gap spacing.",
    status: "Exists",
    source: "src/components/layout/Stack.tsx — built in DS-2.1.2, generalizing the flex flex-col gap-N pattern repeated ad hoc in nearly every component in this codebase.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["Gap tied to the spacing scale", "Align start/center/stretch"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["The single most repeated layout pattern in the entire codebase"],
  },
  {
    id: "inline",
    name: "Inline",
    groupId: "layout-primitives",
    purpose: "A horizontal flex arrangement with consistent gap spacing and wrapping.",
    status: "Exists",
    source: "src/components/layout/Inline.tsx — built in DS-2.1.2, generalizing the flex flex-wrap gap-N pattern repeated alongside Stack's own.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["Gap tied to the spacing scale", "Wrap/no-wrap"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["CrossLinks rows repeated across every DS-1.x page"],
  },
  {
    id: "grid",
    name: "Grid",
    groupId: "layout-primitives",
    purpose: "A general-purpose CSS Grid arrangement with a configurable column count.",
    status: "Exists",
    source: "src/components/layout/Grid.tsx — built in DS-2.1.2 with fixed-column and auto-fit/auto-fill strategies; src/components/layout/CardGrid.tsx remains the specialized wrapper for card collections at its own four fixed breakpoints.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["1–6 columns", "Responsive column collapse"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["The Canonical Workspace Blueprint's own tier-4 peer row"],
  },
  {
    id: "cluster",
    name: "Cluster",
    groupId: "layout-primitives",
    purpose: "A group of items that wrap onto multiple lines while staying visually clustered together.",
    status: "Exists",
    source: "src/components/layout/Cluster.tsx — built in DS-2.1.2, directly on top of Inline rather than reimplementing the same flex-wrap logic a second time.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["Gap tied to the spacing scale"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["Chip/Tag collections"],
  },
  {
    id: "surface",
    name: "Surface",
    groupId: "layout-primitives",
    purpose: "The base elevated-background treatment every panel-like component sits on.",
    status: "Exists",
    source: "src/components/layout/Surface.tsx — built in DS-2.1.2 on the existing semantic elevation shadow scale; GlassPanel.tsx and SurfacePanel.tsx remain their own distinct treatments rather than being migrated onto it.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["Elevation tiers tied to the shadow scale"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["Panel", "Card"],
  },
  {
    id: "panel",
    name: "Panel",
    groupId: "layout-primitives",
    purpose: "A bounded content region with a border and background, one step more structured than a bare Surface.",
    status: "Exists",
    source: "src/components/layout/Panel.tsx — built in DS-2.1.2 directly on Surface; src/components/ui/SurfacePanel.tsx remains its own specific styling of the same concept.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["With header slot", "Bordered/borderless"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["Inspector Workspace region panels"],
  },
  {
    id: "scroll-area",
    name: "Scroll Area",
    groupId: "layout-primitives",
    purpose: "A region that scrolls independently of the page, with a consistently styled scrollbar.",
    status: "Exists",
    source: "src/components/layout/ScrollArea.tsx — built in DS-2.1.2, generalizing the overflow-x-auto pattern every table in this design system already reached for by hand.",
    priority: "Medium",
    requiredStates: ["Default", "Scrolled (shows a fade/shadow edge)"],
    requiredVariants: ["Horizontal", "Vertical", "Both"],
    accessibility: ["Keyboard-scrollable via focus + arrow keys when it contains no other focusable content"],
    reuseTargets: ["Table's own horizontal scroll", "Asset Workspace long lists"],
  },
  {
    id: "separator",
    name: "Separator",
    groupId: "layout-primitives",
    purpose: "A semantic layout-level rule marking a boundary between regions, distinct from Divider's purely visual line within one region.",
    status: "Exists",
    source: "src/components/layout/Separator.tsx — built in DS-2.1.2, generalizing the border-t utility classes applied ad hoc between regions.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["Horizontal", "Vertical"],
    accessibility: ["role=\"separator\" when it carries semantic meaning beyond decoration"],
    reuseTargets: ["SectionShell's own divider prop, once generalized"],
  },
];

export function maturityFor(component: FoundationComponent): MaturityLevel {
  return MATURITY_FROM_STATUS[component.status];
}

export function groupFor(component: FoundationComponent): FoundationGroupDef {
  const group = FOUNDATION_GROUPS.find((g) => g.id === component.groupId);
  if (!group) throw new Error(`Foundation catalog: unknown group id "${component.groupId}"`);
  return group;
}

export interface CatalogSummary {
  total: number;
  byStatus: Record<InventoryStatus, number>;
  byMaturity: Record<MaturityLevel, number>;
  highPriorityGaps: FoundationComponent[];
}

/** Every number here is computed live from FOUNDATION_COMPONENTS — nothing in this summary is hand-typed. */
export function catalogSummary(): CatalogSummary {
  const byStatus: Record<InventoryStatus, number> = { Exists: 0, Partial: 0, Needed: 0 };
  const byMaturity: Record<MaturityLevel, number> = {
    Concept: 0,
    Prototype: 0,
    "Production Ready": 0,
    Certified: 0,
    Locked: 0,
  };
  for (const component of FOUNDATION_COMPONENTS) {
    byStatus[component.status] += 1;
    byMaturity[maturityFor(component)] += 1;
  }
  const highPriorityGaps = FOUNDATION_COMPONENTS.filter(
    (component) => component.priority === "High" && component.status !== "Exists",
  );
  return { total: FOUNDATION_COMPONENTS.length, byStatus, byMaturity, highPriorityGaps };
}
