import { INVENTORY_GROUPS, type InventoryStatus, type InventoryPriority } from "../../inventory/_data/inventory";
import { MATURITY_FROM_STATUS, type MaturityLevel } from "../../_data/maturity";

export type FoundationGroupId =
  | "actions"
  | "inputs"
  | "feedback"
  | "overlays"
  | "navigation"
  | "data-display"
  | "layout-primitives"
  | "operational"
  | "workflow";

export interface FoundationGroupDef {
  id: FoundationGroupId;
  title: string;
  description: string;
}

export const FOUNDATION_GROUPS: FoundationGroupDef[] = [
  { id: "actions", title: "Actions", description: "Buttons and other triggers a user clicks to do something." },
  { id: "inputs", title: "Inputs", description: "Form controls for entering or selecting a value." },
  { id: "feedback", title: "Feedback", description: "Communicating state, status, and outcome back to the user." },
  { id: "overlays", title: "Overlays", description: "Content that floats above the page on demand, dismissed explicitly." },
  { id: "navigation", title: "Navigation", description: "Moving between views, pages, sections, or steps." },
  { id: "data-display", title: "Data Display", description: "Presenting structured content and information at rest." },
  { id: "layout-primitives", title: "Layout Primitives", description: "The composition building blocks every other component is arranged with." },
  { id: "operational", title: "Operational Components", description: "Composed, ready-to-use components built on top of the certified Foundation Layer for real operational screens — not new primitives themselves." },
  { id: "workflow", title: "Workflow Components", description: "The reusable structure multi-step business workflows compose from — built on top of the certified Foundation and Operational layers, framework only, no workflow-specific business logic." },
];

export interface FoundationComponent {
  id: string;
  name: string;
  groupId: FoundationGroupId;
  purpose: string;
  status: InventoryStatus;
  source?: string;
  requiredStates: string[];
  requiredVariants: string[];
  accessibility: string[];
  reuseTargets: string[];
  priority: InventoryPriority;
  /** Set only when this entry's status/source/priority was looked up from the DS-0.2 inventory rather than derived fresh from the codebase. */
  derivedFrom?: string;
}

const ALL_INVENTORY_ITEMS = INVENTORY_GROUPS.flatMap((group) => group.items);

function fromInventory(name: string) {
  const item = ALL_INVENTORY_ITEMS.find((i) => i.name === name);
  if (!item) throw new Error(`Foundation catalog references unknown inventory item: ${name}`);
  return item;
}

const INTERACTIVE_STATES = ["Default", "Hover", "Focus", "Active", "Disabled"];
const FIELD_STATES = ["Default", "Focus", "Disabled", "Error", "Success"];
const FIELD_A11Y = ["Associated <label>", "aria-invalid on error", "aria-describedby for helper/error text", "Full keyboard operability"];

export const FOUNDATION_COMPONENTS: FoundationComponent[] = [
  // Actions
  {
    id: "button",
    name: "Button",
    groupId: "actions",
    purpose: "The primary trigger for a user-initiated action.",
    status: "Exists",
    source: "src/components/ui/Button.tsx",
    priority: "Low",
    requiredStates: [...INTERACTIVE_STATES, "Loading"],
    requiredVariants: ["Primary", "Secondary", "Ghost", "Destructive", "sm/md/lg"],
    accessibility: ["Native <button> or <a> semantics", "Focus ring", "aria-busy while loading", "Disabled blocks activation, not just styling"],
    reuseTargets: ["Every Workspace Toolbar action", "Every Dialog's confirm/cancel pair"],
  },
  {
    id: "icon-button",
    name: "Icon Button",
    groupId: "actions",
    purpose: "A square, icon-only trigger for a single unambiguous action in dense chrome.",
    status: "Partial",
    source: "src/components/ui/Button.tsx (supports a leading icon with empty label, but no dedicated square icon-only mode or enforced aria-label)",
    priority: "High",
    requiredStates: INTERACTIVE_STATES,
    requiredVariants: ["sm/md/lg", "Ghost", "Toggled/pressed"],
    accessibility: ["Required aria-label (no visible text to label it)", "Tooltip on hover/focus for sighted users"],
    reuseTargets: ["Workspace Toolbar dense actions", "Asset Card row actions"],
  },
  {
    id: "button-group",
    name: "Button Group",
    groupId: "actions",
    purpose: "A visually connected row of related buttons, acting as one control.",
    status: "Needed",
    source: "src/components/ui/CTAGroup.tsx (a related row-of-buttons shape, built for marketing CTA spacing, not a connected/segmented group)",
    priority: "Medium",
    requiredStates: INTERACTIVE_STATES,
    requiredVariants: ["Horizontal", "Connected borders", "With dividers"],
    accessibility: ["role=\"group\" with an accessible label"],
    reuseTargets: ["Workspace Toolbar view toggles"],
  },
  {
    id: "dropdown-button",
    name: "Dropdown Button",
    groupId: "actions",
    purpose: "A button that opens a Menu of related actions instead of triggering one directly.",
    status: "Needed",
    source: "No Menu primitive exists yet to build this on — see Menu below.",
    priority: "Medium",
    requiredStates: [...INTERACTIVE_STATES, "Open"],
    requiredVariants: ["Primary", "Secondary", "Ghost"],
    accessibility: ["aria-haspopup=\"menu\"", "aria-expanded", "Arrow-key navigation once open"],
    reuseTargets: ["Batch Action Bar", "Queue Table row actions"],
  },
  {
    id: "split-button",
    name: "Split Button",
    groupId: "actions",
    purpose: "A primary action button paired with an adjoining Dropdown Button for related alternatives.",
    status: "Needed",
    source: "Depends on both Button Group and Dropdown Button, neither of which exist yet.",
    priority: "Low",
    requiredStates: [...INTERACTIVE_STATES, "Open"],
    requiredVariants: ["Primary", "Secondary"],
    accessibility: ["Two independently focusable, independently labeled controls"],
    reuseTargets: ["Publishing Operations primary publish action with channel alternatives"],
  },

  // Inputs
  {
    id: "input",
    name: "Input",
    groupId: "inputs",
    purpose: fromInventory("Input").purpose,
    status: fromInventory("Input").status,
    source: fromInventory("Input").source,
    priority: fromInventory("Input").priority,
    derivedFrom: "DS-0.2 inventory: Input",
    requiredStates: FIELD_STATES,
    requiredVariants: ["Text", "Number", "Password", "With leading/trailing icon"],
    accessibility: FIELD_A11Y,
    reuseTargets: ["Every form field across every DS-2.x operational component"],
  },
  {
    id: "textarea",
    name: "Textarea",
    groupId: "inputs",
    purpose: fromInventory("Textarea").purpose,
    status: fromInventory("Textarea").status,
    source: fromInventory("Textarea").source,
    priority: fromInventory("Textarea").priority,
    derivedFrom: "DS-0.2 inventory: Textarea",
    requiredStates: FIELD_STATES,
    requiredVariants: ["Fixed rows", "Auto-growing"],
    accessibility: FIELD_A11Y,
    reuseTargets: ["Property Editor long-text fields"],
  },
  {
    id: "select",
    name: "Select",
    groupId: "inputs",
    purpose: fromInventory("Select").purpose,
    status: fromInventory("Select").status,
    source: fromInventory("Select").source,
    priority: fromInventory("Select").priority,
    derivedFrom: "DS-0.2 inventory: Select",
    requiredStates: FIELD_STATES,
    requiredVariants: ["Single-select", "Placeholder option"],
    accessibility: FIELD_A11Y,
    reuseTargets: ["Property Editor enum fields"],
  },
  {
    id: "combobox",
    name: "Combobox",
    groupId: "inputs",
    purpose: fromInventory("Combobox").purpose,
    status: "Exists",
    source: "src/components/form/ComboboxField.tsx — built in DS-2.1.5: real typeahead filtering, Arrow/Enter/Escape keyboard support, and the ARIA combobox pattern (role=\"combobox\" + role=\"listbox\").",
    priority: fromInventory("Combobox").priority,
    derivedFrom: "DS-0.2 inventory: Combobox",
    requiredStates: [...FIELD_STATES, "Loading options", "No results"],
    requiredVariants: ["Single-select", "Multi-select", "Async-loaded options"],
    accessibility: [...FIELD_A11Y, "ARIA combobox pattern (listbox + active-descendant)"],
    reuseTargets: ["Provider/capability pickers", "Structured Property Editor fields"],
  },
  {
    id: "checkbox",
    name: "Checkbox",
    groupId: "inputs",
    purpose: fromInventory("Checkbox").purpose,
    status: fromInventory("Checkbox").status,
    source: fromInventory("Checkbox").source,
    priority: fromInventory("Checkbox").priority,
    derivedFrom: "DS-0.2 inventory: Checkbox",
    requiredStates: [...INTERACTIVE_STATES, "Checked", "Indeterminate"],
    requiredVariants: ["Standalone", "With label"],
    accessibility: ["Native checkbox semantics", "Indeterminate set via DOM property, not an attribute"],
    reuseTargets: ["Asset Workspace row/grid multi-select"],
  },
  {
    id: "radio",
    name: "Radio",
    groupId: "inputs",
    purpose: "A single option within a mutually exclusive group.",
    status: "Exists",
    source: "src/components/ui/RadioGroup.tsx (ships as a group, not a standalone single Radio — the common real-world usage)",
    priority: "Low",
    requiredStates: [...INTERACTIVE_STATES, "Checked"],
    requiredVariants: ["Standalone option", "Full group"],
    accessibility: ["role=\"radiogroup\" on the container", "Arrow-key navigation between options"],
    reuseTargets: ["Property Editor mutually-exclusive fields"],
  },
  {
    id: "switch",
    name: "Switch",
    groupId: "inputs",
    purpose: fromInventory("Switch").purpose,
    status: fromInventory("Switch").status,
    source: fromInventory("Switch").source,
    priority: fromInventory("Switch").priority,
    derivedFrom: "DS-0.2 inventory: Switch",
    requiredStates: [...INTERACTIVE_STATES, "Checked"],
    requiredVariants: ["Standalone", "With label"],
    accessibility: ["role=\"switch\" with aria-checked"],
    reuseTargets: ["Property Editor boolean fields", "Feature-flag toggles"],
  },
  {
    id: "slider",
    name: "Slider",
    groupId: "inputs",
    purpose: "Dragging or keying to a numeric value within a range.",
    status: "Exists",
    source: "src/components/ui/Slider.tsx",
    priority: "Low",
    requiredStates: [...INTERACTIVE_STATES, "Dragging"],
    requiredVariants: ["Single thumb", "With value label"],
    accessibility: ["role=\"slider\" with aria-valuemin/max/now", "Arrow-key increment/decrement"],
    reuseTargets: ["Numeric Property Editor fields with a bounded range"],
  },
  {
    id: "date-picker",
    name: "Date Picker",
    groupId: "inputs",
    purpose: "Selecting a calendar date, and optionally a range, through a structured picker rather than free text.",
    status: "Exists",
    source: "src/components/form/DatePickerField.tsx — built in DS-2.1.5 on a native <input type=\"date\">, giving real keyboard grid navigation from the browser itself rather than a custom-built popover. Date range remains a gap.",
    priority: "Medium",
    requiredStates: [...FIELD_STATES, "Open"],
    requiredVariants: ["Single date", "Date range"],
    accessibility: ["Full keyboard grid navigation", "Announces the selected date on change"],
    reuseTargets: ["Publishing schedule fields", "Activity Timeline date filters"],
  },
  {
    id: "file-upload",
    name: "File Upload",
    groupId: "inputs",
    purpose: "Selecting or dragging in one or more files to attach or import.",
    status: "Exists",
    source: "src/components/form/FileUploadField.tsx — built in DS-2.1.5: a drag-and-drop zone wrapping a real, always-present native file input, with a removable file list.",
    priority: "Medium",
    requiredStates: ["Default", "Drag-over", "Uploading", "Error", "Disabled"],
    requiredVariants: ["Single file", "Multi-file", "Drop zone"],
    accessibility: ["Native file input fallback always present, never drag-only"],
    reuseTargets: ["Assets Workspace import", "Provider credential upload"],
  },

  // Feedback
  {
    id: "badge",
    name: "Badge",
    groupId: "feedback",
    purpose: "A small, static label communicating a category or status at a glance.",
    status: "Exists",
    source: "src/components/ui/Badge.tsx",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["neutral", "accent", "success", "warning", "error", "sm/md"],
    accessibility: ["Text conveys meaning, not color alone"],
    reuseTargets: ["Used throughout every DS-1.x page already — the most reused foundation component in the system"],
  },
  {
    id: "chip",
    name: "Chip",
    groupId: "feedback",
    purpose: "A compact, often dismissible token representing one applied filter or selection.",
    status: "Exists",
    source: "src/components/operational/FilterChip.tsx — built in DS-2.5.5, the first standalone reusable Chip (src/components/ui/FilterBar.tsx still only defines an inline FilterChip data shape, unchanged).",
    priority: "Medium",
    requiredStates: [...INTERACTIVE_STATES, "Selected"],
    requiredVariants: ["Static", "Dismissible (with an ×)"],
    accessibility: ["Dismiss control has its own accessible label"],
    reuseTargets: ["Filter Bar active filters"],
  },
  {
    id: "tag",
    name: "Tag",
    groupId: "feedback",
    purpose: "A user- or system-assigned label attached to an item, distinct from a status Badge.",
    status: "Needed",
    source: "src/components/ui/Badge.tsx (the closest visual primitive, but Badge's tone system is status-oriented, not built for arbitrary user labels)",
    priority: "Low",
    requiredStates: ["Default", "Removable"],
    requiredVariants: ["Static", "Removable"],
    accessibility: ["Remove control has its own accessible label"],
    reuseTargets: ["Asset metadata tagging"],
  },
  {
    id: "toast",
    name: "Toast",
    groupId: "feedback",
    purpose: "A brief, self-dismissing notification for something that just happened.",
    status: "Exists",
    source: "src/components/feedback/Toast.tsx — built in DS-2.4. ToastProvider + useToast() push a Notification into a fixed, stacked viewport rendered through the Overlay System's Portal at --z-toast; auto-dismiss pauses on hover/focus. Not yet adopted by any real screen.",
    priority: "High",
    requiredStates: ["Entering", "Visible", "Exiting", "Paused on hover"],
    requiredVariants: ["Success", "Error", "Info", "With action"],
    accessibility: ["ARIA live region, polite by default", "Pauses auto-dismiss on hover/focus"],
    reuseTargets: ["Operational Status Notifications region"],
  },
  {
    id: "alert",
    name: "Alert",
    groupId: "feedback",
    purpose: "A boxed, section-level message for warnings, errors, and other status the user should see inline.",
    status: "Exists",
    source: "src/components/feedback/Alert.tsx — built in DS-2.4, the concrete implementation of what was the Warning Banner inventory item. Also exports the shared FeedbackTone/icon/color map every other tone-aware component in this family (Banner, InlineMessage, Notification, EmptyState) imports from. Not yet adopted by any real screen.",
    priority: fromInventory("Warning Banner").priority,
    derivedFrom: "DS-0.2 inventory: Warning Banner",
    requiredStates: ["Default", "Dismissible"],
    requiredVariants: ["Info", "Success", "Warning", "Error"],
    accessibility: ["role=\"alert\" for errors, role=\"status\" for info/success"],
    reuseTargets: ["Operational Status page-level warnings", "Validation Panel summary"],
  },
  {
    id: "banner",
    name: "Banner",
    groupId: "feedback",
    purpose: "A full-bleed, edge-to-edge strip for page- or workspace-level announcements — distinct from Alert's boxed, inline placement.",
    status: "Exists",
    source: "src/components/feedback/Banner.tsx — built in DS-2.4. src/components/form/UnsavedChangesBanner.tsx is a real, already-shipped instance of this exact shape built directly on Surface+Inline rather than this primitive (see the Foundation Feedback docs page's Promotion Candidates) — not migrated, since this package only builds new components. Not yet adopted by any real screen otherwise.",
    priority: "Medium",
    requiredStates: ["Default", "Dismissible"],
    requiredVariants: ["Info", "Success", "Warning", "Error"],
    accessibility: ["role=\"alert\" for errors, role=\"status\" otherwise"],
    reuseTargets: ["Page- and workspace-level announcements"],
  },
  {
    id: "notification",
    name: "Notification",
    groupId: "feedback",
    purpose: "The presentational icon/title/message/timestamp row Toast stacks — reusable standalone for a future Notification Center.",
    status: "Exists",
    source: "src/components/feedback/Notification.tsx — built in DS-2.4. Deliberately dumb/presentational — Toast owns all timing/stacking/portal logic, this owns only the row's content and layout. Not yet adopted by any real screen.",
    priority: "Medium",
    requiredStates: ["Default", "Dismissible"],
    requiredVariants: ["With timestamp", "With action"],
    accessibility: ["Dismiss control has its own accessible label"],
    reuseTargets: ["Toast's stack", "Future Notification Center"],
  },
  {
    id: "inline-message",
    name: "Inline Message",
    groupId: "feedback",
    purpose: "A compact, borderless icon+text line for feedback that isn't attached to one form field.",
    status: "Exists",
    source: "src/components/feedback/InlineMessage.tsx — built in DS-2.4. Field-level validation stays on src/components/form/FieldError.tsx/FieldHelp.tsx; this is for feedback anywhere else in the UI. Not yet adopted by any real screen.",
    priority: "Low",
    requiredStates: ["Info", "Success", "Warning", "Error"],
    accessibility: ["role=\"alert\" for errors, role=\"status\" otherwise"],
    requiredVariants: ["Info", "Success", "Warning", "Error"],
    reuseTargets: ["Lightweight contextual status anywhere outside a form field"],
  },
  {
    id: "validation-summary",
    name: "Validation Summary",
    groupId: "feedback",
    purpose: "An aggregate list of a form's field errors/warnings, surfaced once at the top of the form.",
    status: "Exists",
    source: "src/components/form/ValidationSummary.tsx (built in DS-2.1.5, before Alert existed) — re-exported unchanged from src/components/feedback/ValidationSummary.tsx in DS-2.4, the same shared-ownership precedent as Navigation's SegmentedControl.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["Error", "Warning", "Mixed"],
    accessibility: ["role=\"alert\" when any error is present, role=\"status\" otherwise"],
    reuseTargets: ["Any form with more than a couple of fields to validate at once"],
  },
  {
    id: "progress",
    name: "Progress Bar",
    groupId: "feedback",
    purpose: "An animated fill bar communicating completion of a task with a knowable duration.",
    status: "Exists",
    source: "src/components/feedback/ProgressBar.tsx — built in DS-2.4, wrapping the motion engine's own Progress primitive (src/motion/primitives/Progress.tsx) for the determinate fill rather than re-animating one from scratch; adds the indeterminate sliding-fill mode, label, and percentage on top. Not yet adopted by any real screen.",
    priority: fromInventory("Progress Indicator").priority,
    derivedFrom: "DS-0.2 inventory: Progress Indicator",
    requiredStates: ["Determinate", "Indeterminate", "Complete", "Error"],
    requiredVariants: ["Linear", "With percentage label"],
    accessibility: ["role=\"progressbar\" with aria-valuenow/min/max"],
    reuseTargets: ["Background Jobs progress fills"],
  },
  {
    id: "progress-ring",
    name: "Progress Ring",
    groupId: "feedback",
    purpose: "A circular counterpart to Progress Bar, for compact dashboard-style summaries where a full-width bar doesn't fit.",
    status: "Exists",
    source: "src/components/feedback/ProgressRing.tsx — built in DS-2.4, the same Determinate/Indeterminate/tone semantics as Progress Bar rendered as an SVG ring instead of a bar. Not yet adopted by any real screen.",
    priority: "Low",
    requiredStates: ["Determinate", "Indeterminate", "Complete", "Error"],
    requiredVariants: ["With percentage label"],
    accessibility: ["role=\"progressbar\" with aria-valuenow/min/max"],
    reuseTargets: ["Dashboard-style compact progress summaries"],
  },
  {
    id: "status-indicator",
    name: "Status Indicator",
    groupId: "feedback",
    purpose: "A persistent, at-a-glance status dot + label, pulsing only for in-progress states.",
    status: "Exists",
    source: "src/components/illustration/StatusIndicator.tsx (built for the illustration engine) — re-exported unchanged from src/components/feedback/StatusIndicator.tsx in DS-2.4, since it already generalizes correctly outside the illustration engine.",
    priority: "Low",
    requiredStates: ["Idle", "Active", "Success", "Warning", "Error"],
    requiredVariants: ["Dot + label"],
    accessibility: ["Text conveys meaning, not color/pulse alone"],
    reuseTargets: ["Any persistent system/entity status display"],
  },
  {
    id: "spinner",
    name: "Spinner",
    groupId: "feedback",
    purpose: "An indeterminate loading indicator for content or an action with no knowable duration.",
    status: "Partial",
    source: "src/components/ui/Button.tsx and SearchInput.tsx (both render a Loader2 icon inline for their own loading state) plus src/components/feedback/LoadingState.tsx (DS-2.4, the full-region overlay variant) — the Inline sm/md/lg variant still has no standalone, reusable Spinner component of its own.",
    priority: "Medium",
    requiredStates: ["Visible"],
    requiredVariants: ["sm/md/lg", "Inline", "Full-region overlay"],
    accessibility: ["aria-hidden with an accompanying text label elsewhere (a spinner alone announces nothing useful)"],
    reuseTargets: ["Any async region without a knowable duration"],
  },
  {
    id: "loading-state",
    name: "Loading State",
    groupId: "feedback",
    purpose: "A full-region loading placeholder — spinner + label, centered — for an async region with no shape to preview yet.",
    status: "Exists",
    source: "src/components/feedback/LoadingState.tsx — built in DS-2.4, the Full-region overlay variant of the Spinner catalog entry. For a shape-accurate placeholder, use Skeleton instead. Not yet adopted by any real screen.",
    priority: "Medium",
    requiredStates: ["Visible"],
    requiredVariants: ["sm/md/lg"],
    accessibility: ["role=\"status\""],
    reuseTargets: ["Any full-region async load with no meaningful shape to preview"],
  },
  {
    id: "skeleton",
    name: "Skeleton",
    groupId: "feedback",
    purpose: "A placeholder shape approximating content that hasn't loaded yet.",
    status: "Exists",
    source: "src/components/ui/Skeleton.tsx, extended in DS-2.4 with a variant prop (text/block/circle) to close the gap already recorded below — re-exported unchanged from src/components/feedback/Skeleton.tsx.",
    priority: "Low",
    requiredStates: ["Loading"],
    requiredVariants: ["Text line", "Block", "Circle (avatar)"],
    accessibility: ["aria-hidden — the loading state itself is announced elsewhere, not per-skeleton"],
    reuseTargets: ["Library Grid loading state"],
  },
  {
    id: "empty-state",
    name: "Empty State",
    groupId: "feedback",
    purpose: "A dedicated placeholder for a region with nothing to show — no data, no results, or a failed load.",
    status: "Exists",
    source: "src/components/feedback/EmptyState.tsx — built in DS-2.4 with a tone prop (neutral default, plus the four semantic tones) so SuccessState/WarningState/ErrorState/InfoState can be thin presets over this same layout rather than four duplicated components. Not yet adopted by any real screen.",
    priority: fromInventory("Error State").priority,
    derivedFrom: "DS-0.2 inventory: Error State",
    requiredStates: ["No data", "No results", "Error"],
    requiredVariants: ["With illustration", "With retry action"],
    accessibility: ["Announced when it replaces previously-visible content"],
    reuseTargets: ["Library Grid/Table empty states", "Diagnostics Panel no-issues state"],
  },
  {
    id: "outcome-state",
    name: "Outcome State (Success/Warning/Error/Info)",
    groupId: "feedback",
    purpose: "A full-block confirmation of an outcome — not an absence of data, a result the system is telling the user about.",
    status: "Exists",
    source: "src/components/feedback/{SuccessState,WarningState,ErrorState,InfoState}.tsx — built in DS-2.4 as thin tone-preset wrappers over EmptyState, each presetting tone and a default icon. Not yet adopted by any real screen.",
    priority: "Medium",
    requiredStates: ["Success", "Warning", "Error", "Info"],
    requiredVariants: ["With action (e.g. retry)"],
    accessibility: ["role=\"alert\" for Error, role=\"status\" for the rest"],
    reuseTargets: ["Any full-page/full-card outcome screen after an action completes"],
  },

  // Overlays
  {
    id: "dialog",
    name: "Dialog",
    groupId: "overlays",
    purpose: "A focused, modal surface that blocks the rest of the page until dismissed.",
    status: "Exists",
    source: "src/components/overlay/Dialog.tsx — built in DS-2.2 on the shared Portal + useFocusTrap + useEscapeKey foundation. Centered, backdrop-dismissible by default, sm/md/full sizes covering the Confirmation/Form/Full content variants. Not yet adopted by any real screen.",
    priority: "High",
    requiredStates: ["Entering", "Open", "Exiting"],
    requiredVariants: ["Confirmation", "Form", "Full content"],
    accessibility: ["Focus trapped inside while open", "Focus returns to the trigger on close", "Escape closes it", "role=\"dialog\" with aria-modal"],
    reuseTargets: ["Destructive confirmations across every DS-2.x package"],
  },
  {
    id: "drawer",
    name: "Drawer",
    groupId: "overlays",
    purpose: "A panel that slides in from an edge without fully blocking the page behind it.",
    status: "Exists",
    source: "src/components/overlay/Drawer.tsx — built in DS-2.2, sharing Dialog's backdrop/focus-trap/Escape machinery but docked to an edge (right or bottom) and translating in along one axis instead of scaling from center. Not yet adopted by any real screen.",
    priority: "High",
    requiredStates: ["Entering", "Open", "Exiting"],
    requiredVariants: ["Right edge", "Bottom edge"],
    accessibility: ["Focus trapped while open", "Escape closes it"],
    reuseTargets: ["Inspector Workspace's Drawer responsive mode", "Operational Status's Drawer responsive mode"],
  },
  {
    id: "popover",
    name: "Popover",
    groupId: "overlays",
    purpose: "A small, anchored surface of contextual content or controls, dismissed on outside click.",
    status: "Exists",
    source: "src/components/overlay/Popover.tsx — built in DS-2.2 on useAnchoredPosition (shared with Menu and Tooltip) plus useFocusTrap/useOutsideClick/useEscapeKey. Not yet adopted by any real screen.",
    priority: "Medium",
    requiredStates: ["Open", "Closed"],
    requiredVariants: ["Anchored to a trigger element"],
    accessibility: ["Dismissed by Escape and outside click", "Focus returns to the trigger on close"],
    reuseTargets: ["Quick health detail from Operational Health"],
  },
  {
    id: "menu",
    name: "Menu",
    groupId: "overlays",
    purpose: "A list of actions or options anchored to a trigger, dismissed on selection or outside click.",
    status: "Exists",
    source: "src/components/overlay/Menu.tsx + MenuItem.tsx — built in DS-2.2. Full ARIA menu pattern (roving tabindex, Up/Down/Home/End, type-ahead), MenuItem composed as JSX children rather than a data-list prop, destructive items rendered in the error tone. Not yet adopted by any real screen.",
    priority: "High",
    requiredStates: ["Open", "Closed", "Item highlighted"],
    requiredVariants: ["Action list", "With icons", "With destructive items separated"],
    accessibility: ["ARIA menu pattern", "Arrow-key navigation", "Type-ahead"],
    reuseTargets: ["Dropdown Button", "Queue Table and Asset Card row actions"],
  },
  {
    id: "tooltip",
    name: "Tooltip",
    groupId: "overlays",
    purpose: "A brief label revealed on hover or focus, clarifying an otherwise unlabeled control.",
    status: "Exists",
    source: "src/components/overlay/Tooltip.tsx — built in DS-2.2. The one component in this family that's self-managed rather than controlled (no real caller needs external open/close control over a tooltip); wraps its trigger and shows on hover or focus alike. Not yet adopted by any real screen.",
    priority: "High",
    requiredStates: ["Hidden", "Visible"],
    requiredVariants: ["Text only"],
    accessibility: ["Triggered by focus as well as hover — never hover-only", "Dismissed by Escape"],
    reuseTargets: ["Icon Button labels", "Truncated text throughout the catalog"],
  },
  {
    id: "command-palette",
    name: "Command Palette",
    groupId: "overlays",
    purpose: "A searchable, keyboard-first overlay for jumping to an action or destination without the mouse.",
    status: "Exists",
    source: "src/components/overlay/CommandPalette.tsx — built in DS-2.2. ARIA combobox/listbox pattern, a global Cmd/Ctrl+K shortcut wired even while closed, results grouped by Actions vs. Navigation destinations. Not yet adopted by any real screen.",
    priority: "Low",
    requiredStates: ["Open", "Closed", "Searching", "No results"],
    requiredVariants: ["Actions", "Navigation destinations"],
    accessibility: ["ARIA combobox/listbox pattern", "Global keyboard shortcut to open"],
    reuseTargets: ["Future Workflow Assistant / AI Operations Center extensions"],
  },

  // Navigation
  {
    id: "tabs",
    name: "Tabs",
    groupId: "navigation",
    purpose: "Switching between several views that share the same context without navigating away.",
    status: "Exists",
    source: "src/components/navigation/Tabs.tsx — built in DS-2.3. Context-based (Tabs/TabsList/Tab/TabPanel), full ARIA tabs pattern with roving tabindex and automatic activation on arrow-key move. Distinct from src/components/ui/SegmentedControl.tsx, the same row-of-buttons-with-one-active pattern but built as a choice input (radiogroup), not a tabpanel/tab-role navigation component — re-exported unchanged as src/components/navigation/SegmentedControl.tsx. Not yet adopted by any real screen.",
    priority: "High",
    requiredStates: ["Selected", "Unselected", "Disabled"],
    requiredVariants: ["Horizontal", "With counts/badges per tab"],
    accessibility: ["ARIA tabs pattern (tablist/tab/tabpanel)", "Arrow-key navigation between tabs"],
    reuseTargets: ["Inspector Workspace region switching"],
  },
  {
    id: "breadcrumbs",
    name: "Breadcrumbs",
    groupId: "navigation",
    purpose: fromInventory("Breadcrumbs").purpose,
    status: "Exists",
    source: "src/components/navigation/Breadcrumbs.tsx — built in DS-2.3. Truncates deep hierarchies behind an overflow trigger that reuses the Overlay System's Menu, rather than a bespoke dropdown. Not yet adopted by any real screen.",
    priority: fromInventory("Breadcrumbs").priority,
    derivedFrom: "DS-0.2 inventory: Breadcrumbs",
    requiredStates: ["Default"],
    requiredVariants: ["With truncation for deep hierarchies"],
    accessibility: ["nav landmark with an accessible label", "aria-current=\"page\" on the last crumb"],
    reuseTargets: ["Workspace Header context region"],
  },
  {
    id: "pagination",
    name: "Pagination",
    groupId: "navigation",
    purpose: "Moving through a large result set page by page.",
    status: "Exists",
    source: "src/components/navigation/Pagination.tsx — built in DS-2.3. Numbered (with ellipsis-aware page range), Prev/next only (\"compact\"), and Load more variants. Not yet adopted by any real screen.",
    priority: "Medium",
    requiredStates: ["Default", "Current page", "Disabled (first/last)"],
    requiredVariants: ["Numbered", "Prev/next only", "Load more"],
    accessibility: ["nav landmark", "aria-current=\"page\" on the active page"],
    reuseTargets: ["Library Table long result sets"],
  },
  {
    id: "stepper",
    name: "Stepper",
    groupId: "navigation",
    purpose: "Showing progress through a fixed, ordered sequence of steps.",
    status: "Exists",
    source: "src/components/navigation/Stepper.tsx — built in DS-2.3. A read-only progress display, not an interactive control; Horizontal/Vertical orientation, Numbered or plain markers. Not yet adopted by any real screen — TimelineComposition and the Production package's gate diagrams remain the closest existing visual precedent, not migrated onto this yet.",
    priority: "Medium",
    requiredStates: ["Upcoming", "Current", "Complete", "Error"],
    requiredVariants: ["Horizontal", "Vertical", "Numbered", "With labels"],
    accessibility: ["Current step announced", "aria-current=\"step\""],
    reuseTargets: ["Approval Panel multi-stage review", "Publishing Operations pipeline stages"],
  },
  {
    id: "sidebar-nav",
    name: "Sidebar Nav",
    groupId: "navigation",
    purpose: "The primary sidebar for moving between an app's top-level sections.",
    status: "Exists",
    source: "src/components/navigation/SideNavigation.tsx — built in DS-2.3. Expanded, Collapsed (icon-only, cascaded to children via NavigationCollapsedContext), and With-section-grouping variants, composed from NavigationSection/NavigationGroup/NavigationItem. Not yet adopted by any real screen.",
    priority: fromInventory("Workspace Navigation").priority,
    derivedFrom: "DS-0.2 inventory: Workspace Navigation",
    requiredStates: ["Default", "Active section", "Collapsed (icon-only)"],
    requiredVariants: ["Expanded", "Collapsed", "With section grouping"],
    accessibility: ["nav landmark with an accessible label", "aria-current=\"page\" on the active item"],
    reuseTargets: ["Workspace Shell's own Navigation region"],
  },
  {
    id: "section-nav",
    name: "Navigation Rail",
    groupId: "navigation",
    purpose: "An in-page anchor nav that highlights the section currently in view while scrolling, or a compact icon rail.",
    status: "Exists",
    source: "src/components/navigation/NavigationRail.tsx — built in DS-2.3, generalizing the scroll-spy pattern hand-built once for src/app/design-system/_components/PlaygroundNav.tsx (same IntersectionObserver config) into a reusable Vertical rail / Horizontal scroll-spy bar component, or a plain compact icon rail when scrollSpy is off. Not yet adopted by any real screen.",
    priority: "Low",
    requiredStates: ["Default", "Active (in view)"],
    requiredVariants: ["Vertical rail", "Horizontal scroll-spy bar"],
    accessibility: ["aria-current on the in-view section link"],
    reuseTargets: ["Long documentation pages like this catalog itself"],
  },
  {
    id: "top-nav",
    name: "Top Navigation",
    groupId: "navigation",
    purpose: "The persistent, app-wide top bar for moving between top-level destinations.",
    status: "Exists",
    source: "src/components/navigation/TopNavigation.tsx — built in DS-2.3, generalizing this design system's own src/components/layout/GlobalNav.tsx (brand slot, sticky/backdrop-blur, horizontal-scroll item row instead of wrapping) into a reusable component. Not yet adopted by any real screen — GlobalNav itself is not yet migrated onto it.",
    priority: "Medium",
    requiredStates: ["Default", "Active item"],
    requiredVariants: ["With brand slot", "With trailing slot (e.g. Command Navigation)"],
    accessibility: ["nav landmark with an accessible label", "aria-current=\"page\" on the active item"],
    reuseTargets: ["This design system's own GlobalNav"],
  },
  {
    id: "tree-nav",
    name: "Tree Navigation",
    groupId: "navigation",
    purpose: "Rows that can contain nested child rows, expandable in place, for genuinely hierarchical data of unknown depth.",
    status: "Exists",
    source: "src/components/navigation/TreeNavigation.tsx — built in DS-2.3. Full ARIA tree pattern (role=\"tree\"/\"treeitem\"/\"group\"), Left/Right expand-or-move-to-child/collapse-or-move-to-parent, Up/Down move between visible items. Not yet adopted by any real screen.",
    priority: "Low",
    requiredStates: ["Collapsed", "Expanded", "Selected"],
    requiredVariants: ["Nested folders/categories"],
    accessibility: ["ARIA tree pattern", "Arrow-key navigation matching the APG tree keyboard model"],
    reuseTargets: ["Asset library folder/category navigation"],
  },
  {
    id: "command-nav",
    name: "Command Navigation",
    groupId: "navigation",
    purpose: "A searchable, keyboard-first way to jump to any action or destination without the mouse.",
    status: "Exists",
    source: "src/components/navigation/CommandNavigation.tsx — built in DS-2.3. A thin visible-trigger wrapper (search icon + shortcut hint) around the Overlay System's existing CommandPalette, which owns all search/keyboard/ARIA logic — not duplicated here. Not yet adopted by any real screen.",
    priority: "Low",
    requiredStates: ["Closed", "Open"],
    requiredVariants: ["Standalone trigger", "Inside TopNavigation's trailing slot"],
    accessibility: ["Delegates entirely to Command Palette's ARIA combobox/listbox pattern and global shortcut"],
    reuseTargets: ["Future Workflow Assistant / AI Operations Center extensions"],
  },
  {
    id: "context-nav",
    name: "Context Navigation",
    groupId: "navigation",
    purpose: "Surfacing the current object and its related destinations — object-based, not path-based like Breadcrumbs.",
    status: "Exists",
    source: "src/components/navigation/ContextNavigation.tsx — built in DS-2.3, matching the Context region already documented on Workspace Header (\"surfacing relationships and related links for the current object\"). Not yet adopted by any real screen.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["With related links"],
    accessibility: ["nav landmark labeled \"Related\" for the links list"],
    reuseTargets: ["Workspace Header context region", "Inspector Workspace object header"],
  },

  // Data Display
  {
    id: "card",
    name: "Card",
    groupId: "data-display",
    purpose: "A bounded surface grouping related content, the base unit nearly everything else is composed from.",
    status: "Exists",
    source: "src/components/ui/Card.tsx",
    priority: "Low",
    requiredStates: ["Default", "Interactive (hover/focus)"],
    requiredVariants: ["sm/md/lg padding", "Interactive/static"],
    accessibility: ["Interactive cards use a real button/link semantic, never a bare clickable div alone"],
    reuseTargets: ["Used throughout every DS-0.3/DS-1.x page already"],
  },
  {
    id: "table",
    name: "Table",
    groupId: "data-display",
    purpose: "Structured, sortable rows and columns of data.",
    status: "Exists",
    source: "src/components/table/ — built in DS-2.1.3 as a 13-component system (Table, TableHeader/Body/Footer/Row/Cell/Head, TableSelectionCell, TableStatusCell, TableActionCell, TableEmptyState, TableLoadingState, TableToolbar), plus src/components/table/ResponsiveRulesTable.tsx added in DS-2.1.7.2, which required extending TableHead with a sticky prop for a pinned left column. Adopted by 3 real pages (workspace-layout, workspace-toolbar, primary-workspace) in DS-2.1.7.2, replacing 3 duplicate implementations. DS-2.1.7.3 (MaturityTable) and DS-2.1.7.4 (InventoryTable) were both attempted next and both reverted: migrating either onto Table produced a measured mobile regression (640px and 774px natural width against a 333px viewport, respectively) because Table has no responsive row-collapse capability — confirmed twice, independently. DS-2.1.7.5 (ScorecardTable), DS-2.1.7.6 (CertificationMatrix), and DS-2.1.7.7 (CoverageMatrix) each ran an explicit architecture check first, confirmed a genuine native <table> matching ResponsiveRulesTable's shape, and shipped — all three reusing the DS-2.1.7.2 sticky prop with zero new API surface, cutting the files from 70 to 48, 89 to 68, and 56 to 41 lines respectively. This completed migration of every genuine native <table> in the codebase, across 5 real pages. DS-2.1.8 ran the family's first per-component accessibility pass, confirmed the API is stable (zero changes needed across the last three migrations), and certified the family — the first in this audit to reach that bar. MaturityTable and InventoryTable remain blocked on the row-collapse gap; that's a Future Extension, not a certification blocker. Status: Certified.",
    priority: "High",
    requiredStates: ["Default row", "Selected row", "Loading", "Empty"],
    requiredVariants: ["Sortable columns", "Sticky first column", "Row selection", "Responsive row collapse (confirmed gap — DS-2.1.7.3)"],
    accessibility: ["Native <table> with scope on header cells", "Sort state announced", "DS-2.1.8 found 2 minor gaps: TableLoadingState and TableToolbar lack a screen-reader announcement for their state changes"],
    reuseTargets: ["Queue Table", "Library Table"],
  },
  {
    id: "list",
    name: "List",
    groupId: "data-display",
    purpose: "A vertical sequence of related items, each with a consistent internal layout.",
    status: "Needed",
    source: "Hand-rolled <ul>/<li> rows recur across nearly every DS-1.x principles/checklist section — never generalized into one component.",
    priority: "Medium",
    requiredStates: ["Default item", "Selected item", "Empty"],
    requiredVariants: ["Simple", "With leading icon/avatar", "Divided"],
    accessibility: ["Native list semantics (ul/li)"],
    reuseTargets: ["Recommendation Card lists", "Activity Timeline entries"],
  },
  {
    id: "description-list",
    name: "Description List",
    groupId: "data-display",
    purpose: "A set of label/value pairs, presented as rows.",
    status: "Exists",
    source: "src/components/layout/DescriptionList.tsx — built in DS-2.1.2, generalizing the dl/dt/dd row pattern that had been hand-rolled identically across every DS-1.x Accessibility section since DS-1.2. Also documented as a Foundation Metadata component (src/components/metadata/DescriptionList.tsx re-exports it). Adopted by all 9 real duplicate implementations in DS-2.1.7.1 — the Foundation Layer's first production adoption. Status: Adoption In Progress, not Certified.",
    priority: "High",
    requiredStates: ["Default row"],
    requiredVariants: ["Stacked (mobile)", "Side-by-side (desktop)"],
    accessibility: ["Native dl/dt/dd semantics"],
    reuseTargets: ["Every DS-1.x page's Accessibility section", "Property Editor read-only fields"],
  },
  {
    id: "stat",
    name: "Stat",
    groupId: "data-display",
    purpose: "A single labeled metric, sized for a dashboard or summary row.",
    status: "Exists",
    source: "src/components/ui/StatCard.tsx",
    priority: "Low",
    requiredStates: ["Default", "With trend indicator"],
    requiredVariants: ["Compact", "With icon"],
    accessibility: ["Value and label both in the accessible name — a number alone announces nothing"],
    reuseTargets: ["Metrics Card", "Catalog Summary counts"],
  },
  {
    id: "avatar",
    name: "Avatar",
    groupId: "data-display",
    purpose: "A compact visual representation of a person, team, or provider.",
    status: "Needed",
    priority: "Medium",
    requiredStates: ["Image loaded", "Fallback initials", "Fallback icon"],
    requiredVariants: ["sm/md/lg", "Single", "Stacked group"],
    accessibility: ["Accessible name via alt text or aria-label, never image-only with no name"],
    reuseTargets: ["Live Team Presence future extension", "Job Status Card triggered-by"],
  },
  {
    id: "icon",
    name: "Icon",
    groupId: "data-display",
    purpose: "A single glyph from the design system's icon set, sized and colored consistently.",
    status: "Partial",
    source: "lucide-react icons are imported and sized directly wherever needed (e.g. size-3.5, size-4) — consistent by convention, not enforced by a wrapping Icon component or token-driven size scale.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["xs/sm/md/lg sizes tied to spacing tokens"],
    accessibility: ["aria-hidden by default; accessible name only when the icon is the sole content of a control"],
    reuseTargets: ["Every component in this catalog that renders an icon"],
  },
  {
    id: "divider",
    name: "Divider",
    groupId: "data-display",
    purpose: "A thin visual line separating content within a single region.",
    status: "Needed",
    source: "border-t/border-b border-border-subtle utility classes are applied ad hoc wherever a divider is needed, rather than through one component.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["Horizontal", "Vertical"],
    accessibility: ["aria-hidden — purely visual"],
    reuseTargets: ["Card internal section breaks throughout the catalog"],
  },

  // Layout Primitives
  {
    id: "stack",
    name: "Stack",
    groupId: "layout-primitives",
    purpose: "A vertical flex arrangement with consistent gap spacing.",
    status: "Exists",
    source: "src/components/layout/Stack.tsx — built in DS-2.1.2, generalizing the flex flex-col gap-N pattern repeated ad hoc in nearly every component in this codebase.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["Gap tied to the spacing scale", "Align start/center/stretch"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["The single most repeated layout pattern in the entire codebase"],
  },
  {
    id: "inline",
    name: "Inline",
    groupId: "layout-primitives",
    purpose: "A horizontal flex arrangement with consistent gap spacing and wrapping.",
    status: "Exists",
    source: "src/components/layout/Inline.tsx — built in DS-2.1.2, generalizing the flex flex-wrap gap-N pattern repeated alongside Stack's own.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["Gap tied to the spacing scale", "Wrap/no-wrap"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["CrossLinks rows repeated across every DS-1.x page"],
  },
  {
    id: "grid",
    name: "Grid",
    groupId: "layout-primitives",
    purpose: "A general-purpose CSS Grid arrangement with a configurable column count.",
    status: "Exists",
    source: "src/components/layout/Grid.tsx — built in DS-2.1.2 with fixed-column and auto-fit/auto-fill strategies; src/components/layout/CardGrid.tsx remains the specialized wrapper for card collections at its own four fixed breakpoints.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["1–6 columns", "Responsive column collapse"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["The Canonical Workspace Blueprint's own tier-4 peer row"],
  },
  {
    id: "cluster",
    name: "Cluster",
    groupId: "layout-primitives",
    purpose: "A group of items that wrap onto multiple lines while staying visually clustered together.",
    status: "Exists",
    source: "src/components/layout/Cluster.tsx — built in DS-2.1.2, directly on top of Inline rather than reimplementing the same flex-wrap logic a second time.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["Gap tied to the spacing scale"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["Chip/Tag collections"],
  },
  {
    id: "surface",
    name: "Surface",
    groupId: "layout-primitives",
    purpose: "The base elevated-background treatment every panel-like component sits on.",
    status: "Exists",
    source: "src/components/layout/Surface.tsx — built in DS-2.1.2 on the existing semantic elevation shadow scale; GlassPanel.tsx and SurfacePanel.tsx remain their own distinct treatments rather than being migrated onto it.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["Elevation tiers tied to the shadow scale"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["Panel", "Card"],
  },
  {
    id: "panel",
    name: "Panel",
    groupId: "layout-primitives",
    purpose: "A bounded content region with a border and background, one step more structured than a bare Surface.",
    status: "Exists",
    source: "src/components/layout/Panel.tsx — built in DS-2.1.2 directly on Surface; src/components/ui/SurfacePanel.tsx remains its own specific styling of the same concept.",
    priority: "Medium",
    requiredStates: ["Default"],
    requiredVariants: ["With header slot", "Bordered/borderless"],
    accessibility: ["Layout-only — no semantic role of its own"],
    reuseTargets: ["Inspector Workspace region panels"],
  },
  {
    id: "scroll-area",
    name: "Scroll Area",
    groupId: "layout-primitives",
    purpose: "A region that scrolls independently of the page, with a consistently styled scrollbar.",
    status: "Exists",
    source: "src/components/layout/ScrollArea.tsx — built in DS-2.1.2, generalizing the overflow-x-auto pattern every table in this design system already reached for by hand.",
    priority: "Medium",
    requiredStates: ["Default", "Scrolled (shows a fade/shadow edge)"],
    requiredVariants: ["Horizontal", "Vertical", "Both"],
    accessibility: ["Keyboard-scrollable via focus + arrow keys when it contains no other focusable content"],
    reuseTargets: ["Table's own horizontal scroll", "Asset Workspace long lists"],
  },
  {
    id: "separator",
    name: "Separator",
    groupId: "layout-primitives",
    purpose: "A semantic layout-level rule marking a boundary between regions, distinct from Divider's purely visual line within one region.",
    status: "Exists",
    source: "src/components/layout/Separator.tsx — built in DS-2.1.2, generalizing the border-t utility classes applied ad hoc between regions.",
    priority: "Low",
    requiredStates: ["Default"],
    requiredVariants: ["Horizontal", "Vertical"],
    accessibility: ["role=\"separator\" when it carries semantic meaning beyond decoration"],
    reuseTargets: ["SectionShell's own divider prop, once generalized"],
  },

  // Operational
  {
    id: "data-grid",
    name: "Data Grid",
    groupId: "operational",
    purpose: "A composed, ready-to-use grid — search, filters, sortable columns, row selection, bulk actions, and pagination — for any operational screen with rows to manage.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.1, the first Operational Component built on the certified Foundation Layer. Composes Foundation Table (Table/TableHeader/TableBody/TableRow/TableHead/TableCell/TableSelectionCell/TableEmptyState/TableLoadingState/TableToolbar/TableFooter), Foundation Forms (SearchInput, Select), Foundation Navigation (Pagination), and the Overlay System (Popover, for DataGridColumnPicker) end to end rather than reimplementing any of them. Not yet adopted by any real screen — a dedicated audit (see the Data Grid docs page's own Promotion Candidates section) found zero existing hand-rolled operational grids anywhere in the codebase for Publishing Queue, Commerce Orders, Inventory, Products, Assets, Diagnostics, or Metrics; this is genuinely new capability, not a migration target.",
    priority: "High",
    requiredStates: ["Loading", "Empty", "Filtered", "Selected", "Error", "Read Only", "Busy"],
    requiredVariants: ["Simple", "Selectable", "Filterable", "Searchable", "Bulk action", "Dense", "Inspector (compact/sortable)", "Large dataset (paginated)"],
    accessibility: ["Native <table> semantics throughout (real <th scope>, aria-sort, aria-selected)", "Required caption prop for a real accessible name", "Focus never trapped — only DataGridColumnPicker's Popover opens a floating surface"],
    reuseTargets: ["Publishing Queue", "Commerce Orders", "Inventory", "Products", "Assets", "Diagnostics", "Metrics"],
  },
  {
    id: "inspector-panel",
    name: "Inspector Panel",
    groupId: "operational",
    purpose: "The standard inspector shell for a single selected object — header identity, collapsible property sections, validation, status, history, and object-level actions.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.2, the second Operational Component built on the certified Foundation Layer. Composes Foundation Metadata (IdentityBlock, PropertyGroup, MetadataField, PropertySection), Foundation Forms (any field component as an edit-mode child), Foundation Feedback (ValidationSummary, StatusIndicator, LoadingState, EmptyState), Foundation Navigation (Tabs), and Foundation Layout (Surface, ScrollArea, Inline) end to end. Not yet adopted by any real screen — a dedicated audit found no full inspector implementation anywhere in src/app (Production, Publishing, Commerce, Products, QA, Settings all clean), but did find a real, grep-verified duplicate one level down: src/platforms/components/PlatformDetailsPanel.tsx, src/capabilities/components/CapabilityDetails.tsx, and src/workflows/components/WorkflowStepDetails.tsx all hand-roll the same expandable-detail-panel shell InspectorSection/InspectorGroup now generalize (see the Inspector Panel docs page's own Promotion Candidates section) — not migrated in this package, which only builds new components.",
    priority: "High",
    requiredStates: ["Loading", "Empty", "Read-only", "Editing", "Validation Errors", "Warnings", "Success", "Busy"],
    requiredVariants: ["Simple", "Asset", "Publishing", "Commerce", "Validation", "History", "Read-only", "Multi-section (tabbed)"],
    accessibility: ["Section headings are real buttons with aria-expanded, not decorative labels", "Inherits Navigation's full ARIA tabs pattern unchanged for InspectorTabs", "Validation announcements come from Feedback's ValidationSummary live region, not a second one layered on top"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Products", "QA", "Settings", "src/platforms/components/PlatformDetailsPanel.tsx", "src/capabilities/components/CapabilityDetails.tsx", "src/workflows/components/WorkflowStepDetails.tsx"],
  },
  {
    id: "property-panel",
    name: "Property Panel",
    groupId: "operational",
    purpose: "The standard property-editing experience for a single selected object — labeled rows switching between a read-only value and a real editor, grouped and sectioned.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.3, the third Operational Component built on the certified Foundation Layer. Reuses Inspector Panel's own shell/section/group/action components directly (PropertyPanel/PropertySection/PropertyGroup/PropertyActions are thin re-exports of InspectorPanel/InspectorSection/InspectorGroup/InspectorActions, and Header/Footer are Inspector Panel's InspectorHeader/InspectorFooter with no new file at all) rather than a second copy of the same chrome. New composition: PropertyRow/PropertyLabel/PropertyValue (Foundation Metadata's MetadataLabel/MetadataValue) plus PropertyToggle/PropertySelect/PropertyNumber (thin presets over Foundation Forms' SwitchField/SelectField/InputField) and PropertyEditor (a single-field type dispatcher, distinct in scope from src/components/form/PropertyEditor.tsx's own multi-field FormRow grid). PropertyColor is a genuinely new component — Foundation Forms has no color field yet, a real gap this package surfaces rather than works around silently. Not yet adopted by any real screen — a dedicated audit found no hand-rolled property-editing panel anywhere in src/app across all six named domains; the only stale finding was the DS-0.2 inventory's own \"Property Editor\" entry still marked status: \"Needed\" despite src/components/form/PropertyEditor.tsx already existing (see the Property Panel docs page's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["Read-only", "Editing", "Modified", "Unsaved", "Error", "Warning", "Disabled", "Loading"],
    requiredVariants: ["Basic Properties", "Grouped Properties", "Appearance", "Publishing", "Commerce", "Advanced Settings", "Read-only", "Mixed Editors"],
    accessibility: ["Every editor is a real, natively focusable/operable control (native button/select/number/color inputs)", "Labels are always real, associated <label> elements, never a placeholder standing in for one", "PropertyReset carries a real aria-label, not an icon-only control with no accessible name"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Products", "QA", "Settings"],
  },
  {
    id: "asset-browser",
    name: "Asset Browser",
    groupId: "operational",
    purpose: "The canonical browsing experience for any asset library — search, filter, grid/list toggle, selection, pagination, and an optional inspector slot for the selected item.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.4, the fourth Operational Component built on the certified Foundation Layer. Composes Foundation Layout (Grid), Foundation Table (via Data Grid, for list view), Foundation Metadata, Foundation Forms, Foundation Feedback, Foundation Navigation (SegmentedControl, Pagination), and Foundation Overlay end to end, plus Operational Data Grid (AssetList delegates directly to DataGrid), Inspector Panel, and Property Panel (composed live in the docs gallery's List View demo, passed through the inspector slot). AssetSearch/AssetFilters/AssetBrowserToolbar are thin re-exports of Data Grid's own Search/Filters/Toolbar; useAssetSelection/AssetSelectionSummary are renamed re-exports of Data Grid's selection hook/summary. Not yet adopted by any real screen — a dedicated audit found zero existing hand-rolled asset/library browsing UI anywhere in the codebase across all eight named domains, including a specific check (and disproof) of this repo's own four MS-2.x Library Playground pages, which are pure diagram galleries with no search/filter/selection code (see the Asset Browser docs page's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["Loading", "Empty", "Searching", "Filtered", "Selected", "Busy", "Error", "Read-only"],
    requiredVariants: ["Image Library", "Artwork Library", "Product Library", "Style Library", "Document Library", "Mixed Assets", "Grid View (paginated)", "List View (with Inspector)"],
    accessibility: ["View toggle inherits Navigation's full ARIA radiogroup pattern via SegmentedControl unchanged", "Selection checkboxes are always visible (never hover-only), keyboard- and touch-discoverable", "List view inherits Data Grid's native <table> semantics unchanged; grid view cards are real role=\"button\" elements with Enter/Space activation when clickable"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Products", "Styles", "Blueprints", "Overlays", "Recipes"],
  },
  {
    id: "filter-search-system",
    name: "Filter & Search System",
    groupId: "operational",
    purpose: "The standard discovery experience — search with scope and suggestions, multi-value filter dimensions, sort, saved filters, active-filter chips, and a result count — used throughout every StudioPOD library, queue, and operational workspace.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.5, the fifth Operational Component built on the certified Foundation Layer. Composes Foundation Forms (SearchInput, Checkbox, Select), Foundation Metadata, Foundation Navigation (SegmentedControl), Foundation Overlay (Popover), and Foundation Feedback end to end, plus Operational Data Grid (SearchField re-exports DataGridSearch) and Asset Browser directly. Also resolved a real pre-existing duplication: Data Grid's DataGridPagination and Asset Browser's AssetPagination each inlined an identical \"X–Y of Z\" calculation; both now delegate to this package's own ResultSummary. FilterChip is also the first standalone Chip the Foundation Component Catalog has tracked as Needed since DS-2.1.1. Not yet adopted by any real screen — a dedicated audit found zero existing hand-rolled search/filter/sort UI anywhere in the codebase across all eight named domains, including a fresh re-check of the four MS-2.x Library Playground pages (see this package's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["Empty", "Searching", "Filtered", "No Results", "Loading", "Busy", "Saved", "Modified"],
    requiredVariants: ["Simple Search", "Global Search", "Library Search", "Queue Search", "Inspector Search", "Advanced Filtering", "Saved Filters", "Combined Search + Filter"],
    accessibility: ["SearchSuggestions/SearchHistory select via onMouseDown+preventDefault so a field's onBlur never closes the list before the click registers, the same fix ComboboxField already established", "FilterPopover inherits the Overlay System's own focus-trap-in/restore-on-close guarantee unchanged", "Every FilterChip rendered by ActiveFilterList carries its own accessible remove label, never an icon alone"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Products", "Assets", "Recipes", "Blueprints", "Libraries"],
  },
  {
    id: "bulk-actions-system",
    name: "Bulk Actions System",
    groupId: "operational",
    purpose: "The standard experience for performing operations on multiple selected items — a bulk-action bar, confirmation gate, live progress, results with per-item conflicts, and an undo window — used across every StudioPOD platform.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.6, the sixth Operational Component built on the certified Foundation Layer. Composes Foundation Overlay (Dialog for confirmation, Menu for overflow actions), Foundation Feedback (ProgressBar, StatusIndicator, Alert, Notification), Foundation Forms, and Foundation Navigation end to end, plus Operational Data Grid (BulkSelectionSummary re-exports DataGridSelectionSummary; BulkActionBar composes Foundation Table's own TableToolbar bulk-mode chrome), Asset Browser, and Filter & Search directly. Not yet adopted by any real screen — a dedicated audit found zero existing hand-rolled bulk-action UI anywhere in the codebase across all seven named domains, including a fresh re-check of the four MS-2.x Library Playground pages (see this package's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["No Selection", "Selected", "Processing", "Completed", "Partial Success", "Failed", "Cancelled", "Undo Available"],
    requiredVariants: ["Simple Selection", "Library Bulk Actions", "Grid Bulk Actions", "Queue Bulk Actions", "Confirmation Flow", "Progress Flow", "Conflict Resolution", "Undo Flow"],
    accessibility: ["BulkActionMenu inherits Foundation Overlay's Menu ARIA menu pattern (roving highlight, type-ahead, Enter/Escape) unchanged", "BulkActionConfirmation always sets labelledBy/describedBy on Dialog so its title and consequences text are announced together, not just \"dialog\"", "BulkResults' role=\"alert\" vs role=\"status\" choice comes from Alert's own feedbackRole(tone) helper, not a second convention"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Products", "Assets", "Queues", "Libraries"],
  },
  {
    id: "status-health-system",
    name: "Status & Health System",
    groupId: "operational",
    purpose: "The standard operational health surface — a summary, health score, metrics, issues, recommendations, timeline, alerts, and provider status — used across every StudioPOD platform.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.7, the seventh Operational Component built on the certified Foundation Layer. Composes Foundation Metadata (StatusSummary, StatGroup/StatCard), Foundation Feedback (StatusIndicator, ProgressRing, Alert), and Foundation Table end to end, plus Operational Inspector Panel (StatusPanel re-exports InspectorPanel; StatusTimeline re-exports InspectorHistory; HealthPanel composes InspectorHeader/InspectorSection directly) and Operational Data Grid (ProviderHealthPanel) directly. Resolved several real, pre-existing name/scope collisions rather than duplicating them: StatusSummary and StatusMetric are re-exports of Foundation Metadata's own StatusSummary/StatCard; this operational HealthIndicator is a distinct eight-state preset from src/illustrations/primitives/HealthIndicator.tsx's own three-state diagram-node version, documented as such. Not yet adopted by any real screen — a dedicated audit (including a deep read of Production's own three existing health files) found no duplicate score/issue-list/recommendation abstraction anywhere in the codebase across all six named domains (see this package's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["Healthy", "Warning", "Critical", "Offline", "Syncing", "Paused", "Recovering", "Unknown"],
    requiredVariants: ["Platform Health", "Publishing Health", "Commerce Health", "Provider Health", "Sync Status", "Validation Health", "Operational Dashboard", "Incident View"],
    accessibility: ["HealthIndicator always pairs its dot with a text label, never color alone", "HealthScore's role=\"progressbar\" and aria-valuenow come from Foundation Feedback's own ProgressRing unchanged", "OperationalAlertPanel's role=\"alert\" vs role=\"status\" choice comes from Alert's own feedbackRole(tone) helper, not a second convention"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Intelligence", "Operations", "Diagnostics"],
  },
  {
    id: "queue-job-system",
    name: "Queue & Job System",
    groupId: "operational",
    purpose: "The standard operational execution interface for every queued workflow — a job queue with status, priority, and inline progress, plus per-job detail, retry, results, and error handling.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.8, the eighth Operational Component built on the certified Foundation Layer. Composes Foundation Table (Table/TableRow/TableCell/TableSelectionCell/TableActionCell/TableToolbar directly — QueueRow is real table markup, not Data Grid's generic column/accessor system, since a queue row's shape is fixed), Foundation Feedback (StatusIndicator, Alert), and Foundation Navigation (SegmentedControl) end to end, plus Operational Data Grid (selection helpers, DataGridEmptyState re-exported as QueueEmptyState), Bulk Actions (BulkActionBar for selected jobs; JobProgress re-exports BulkProgress; JobRetry composes BulkActionButton/BulkActionConfirmation directly), and Status & Health (JobCard composes StatusPanel/InspectorHeader/InspectorSection; JobTimeline re-exports StatusTimeline) directly. Not yet adopted by any real screen — a dedicated audit (including a direct read of the Workflow Diagram Library's own WorkflowCard/WorkflowProgress/WorkflowTimeline) found no duplicate job-queue implementation anywhere in the codebase across all five named domains (see this package's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["Queued", "Running", "Completed", "Failed", "Retrying", "Paused", "Cancelled", "Blocked"],
    requiredVariants: ["Publishing Queue", "Production Queue", "Commerce Queue", "Retry Queue", "Failed Jobs", "Completed Jobs", "Live Queue", "Job Detail"],
    accessibility: ["QueueFilters inherits Foundation Navigation's SegmentedControl roving-tabindex radiogroup unchanged", "JobProgress's role=\"progressbar\" and aria-valuenow come from Foundation Feedback's own ProgressBar (via BulkProgress) unchanged", "JobRetry's confirmation dialog inherits BulkActionConfirmation's focus-trap-in/restore-on-close guarantee"],
    reuseTargets: ["Publishing", "Production", "Commerce", "Automation", "Operations"],
  },
  {
    id: "dashboard-widget-system",
    name: "Dashboard Widget System",
    groupId: "operational",
    purpose: "The standard dashboard framework for every platform — a responsive widget grid of metric, trend, chart, status, activity, queue, health, and recommendation tiles, plus the titled sections and empty state that hold them.",
    status: "Exists",
    source: "src/components/operational/ — built in DS-2.5.9, the ninth Operational Component built on the certified Foundation Layer. Composes Foundation Layout (Grid in auto-fit mode underneath DashboardGrid, Panel as every widget's shell), Foundation Metadata (StatGroup for multi-metric widgets), and Foundation Feedback (EmptyState underneath DashboardEmptyState, LoadingState underneath DashboardSection's refresh state) end to end, plus Operational Status & Health (HealthScore/HealthIssueList/HealthIndicator/HealthRecommendation composed directly by HealthWidget/StatusWidget/RecommendationWidget) and Queue & Job (JobTimeline composed by ActivityWidget; Queue composed by QueueWidget) directly. MetricCard/KPIWidget/TrendWidget add a tone-aware trend renderer and TrendWidget/ChartWidget add minimal inline-SVG chart marks — genuinely new capability, since no trend vocabulary or charting primitive existed anywhere in the codebase before this package. Not yet adopted by any real screen — a dedicated audit across six named domains found no duplicate widget-grid implementation, only a narrow, already-documented overlap with Production's own HealthDashboardDiagram (see this package's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["Loading", "Refreshing", "Healthy", "Warning", "Critical", "Empty", "Error", "Read-only"],
    requiredVariants: ["Executive Dashboard", "Production Dashboard", "Publishing Dashboard", "Commerce Dashboard", "Operations Dashboard", "Health Dashboard", "Queue Dashboard", "Analytics Dashboard"],
    accessibility: ["ChartWidget pairs its SVG bars with a role=\"img\" aria-label summarizing every label/value pair, never relying on the graphic alone", "MetricCard's/TrendWidget's trend direction is conveyed by an arrow icon and the value's own sign, not color alone", "DashboardEmptyState/DashboardSection's loading state inherit EmptyState's/LoadingState's own role=\"status\" unchanged"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Operations", "Intelligence", "Admin"],
  },
  {
    id: "workflow-framework",
    name: "Workflow Framework",
    groupId: "workflow",
    purpose: "The reusable structure every business workflow composes from — a header/sidebar/stage/step/transition/progress/summary/actions/footer shell, with no workflow-specific business logic of its own.",
    status: "Exists",
    source: "src/components/workflow/ — built in DS-3.1, the first package of the new Workflow Component Library tier sitting on top of the certified Operational layer. Composes Foundation Metadata (IdentityBlock underneath WorkflowHeader, StatGroup underneath WorkflowSummary), Foundation Feedback (StatusIndicator underneath WorkflowStatus, ProgressBar underneath WorkflowProgress), Foundation Layout (Grid underneath WorkflowStageGroup, Surface/ScrollArea underneath WorkflowSidebar), and Operational Inspector Panel (InspectorPanel composed directly by the root Workflow component; InspectorFooter/InspectorActions re-exported verbatim as WorkflowFooter/WorkflowActions) directly. WorkflowStage/WorkflowStep/WorkflowTransition are genuinely new — Foundation Navigation's own Stepper was evaluated and ruled out as a base, since its single current-index/error-index model can't represent eight independently-statused steps at once. Not yet adopted by any real screen — a dedicated audit (including a direct read of the pre-existing Workflow Diagram Library's own eight components) found no duplicate stage/step/transition implementation anywhere in the codebase across all six named domains (see this package's own Promotion Candidates section). WorkflowStep and WorkflowProgress share names with pre-existing, differently-scoped exports in src/workflows/ and src/compositions/ — documented explicitly in each file's own doc comment rather than renamed, since nothing is actually duplicated.",
    priority: "High",
    requiredStates: ["Not Started", "Ready", "Running", "Waiting", "Blocked", "Completed", "Failed", "Cancelled"],
    requiredVariants: ["Linear Workflow", "Branching Workflow", "Approval Workflow", "Publishing Workflow", "Production Workflow", "Commerce Workflow", "Long-running Workflow", "Read-only Workflow"],
    accessibility: ["WorkflowStep renders a real <button> only when onClick is supplied, never a div-with-onClick", "WorkflowStatus always pairs its dot with a text label, never color alone", "WorkflowProgress's role=\"progressbar\" and aria-valuenow come from Foundation Feedback's own ProgressBar unchanged"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Intelligence", "Planning", "Automation"],
  },
  {
    id: "workflow-stepper",
    name: "Workflow Stepper",
    groupId: "workflow",
    purpose: "The standard guided wizard experience for multi-step processes — a numbered stepper bar, Back/Next navigation, and per-step status, composing the Workflow Framework directly rather than duplicating it.",
    status: "Exists",
    source: "src/components/workflow/ — built in DS-3.2, the second package of the Workflow Component Library. Six of its ten components are pure re-exports of Workflow Framework's own components (WorkflowStepper=Workflow, WorkflowStepperHeader=WorkflowHeader, WorkflowStepperStage=WorkflowStage, WorkflowStepperSummary=WorkflowSummary, WorkflowStepperActions=WorkflowActions, WorkflowStepperFooter=WorkflowFooter); WorkflowStepperConnector is a thin wrapper over WorkflowTransition (adding a horizontal, stretch-to-fill default) and WorkflowStepperProgress is a thin wrapper over WorkflowProgress (computing a \"Step N of M\" label, the same pattern Bulk Actions' own BulkProgress already established one layer below). WorkflowStepperStep and WorkflowStepperNavigation are genuinely new: WorkflowStepperStep needs its own 8-value status vocabulary (Current merges Workflow Framework's own Ready/Running; Skipped has no equivalent in either Workflow Framework's or Foundation Navigation's own Stepper vocabulary, confirmed by direct comparison before building it) rendered in Foundation Navigation's own Stepper visual idiom (circular marker, horizontal/vertical orientation) rather than Stepper's own code, since Stepper's single current-index/error-index model can't represent Waiting or Skipped either. WorkflowStepperNavigation was built fresh rather than reusing Foundation Navigation's own Pagination, whose compact variant is visually close but carries page-list ARIA wording (\"Pagination,\" \"Previous/Next page\") that would misdescribe a step wizard. Not yet adopted by any real screen — a dedicated audit across six named domains (including Foundation Navigation's own Stepper.tsx catalog entry, whose reuseTargets already named \"Approval Panel multi-stage review\" and \"Publishing Operations pipeline stages\" as gaps this package now fills) found no duplicate stepper/wizard implementation anywhere in the codebase (see this package's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["Not Started", "Current", "Completed", "Blocked", "Waiting", "Skipped", "Failed", "Cancelled"],
    requiredVariants: ["Linear Wizard", "Product Setup", "Publishing Wizard", "Commerce Setup", "Approval Wizard", "Resume Later", "Read-only Review", "Completed Workflow"],
    accessibility: ["WorkflowStepperStep renders a real <button> only when onClick is supplied, never a div-with-onClick", "WorkflowStepperNavigation's Back/Next carry their own step-wizard aria-labels rather than Pagination's page-list wording", "WorkflowStepperStep never relies on marker color alone — Completed/Failed/Blocked/Skipped/Cancelled each pair their tone with a distinct icon or a struck-through label"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Planning", "Onboarding", "Settings"],
  },
  {
    id: "workflow-timeline",
    name: "Workflow Timeline",
    groupId: "workflow",
    purpose: "The standard chronological view of workflow execution, history, approvals, and state transitions — grouped, markered, and connected events, composing the Workflow Framework directly rather than duplicating it.",
    status: "Exists",
    source: "src/components/workflow/ — built in DS-3.3, the third package of the Workflow Component Library. Four of its ten components are pure re-exports of Workflow Framework's own components (WorkflowTimeline=Workflow, WorkflowTimelineHeader=WorkflowHeader, WorkflowTimelineSummary=WorkflowSummary, WorkflowTimelineFooter=WorkflowFooter) and WorkflowTimelineConnector is a thin wrapper over WorkflowTransition (vertical-first default, since a chronological timeline reads top-to-bottom rather than left-to-right). WorkflowTimelineMarker, WorkflowTimelineEvent, WorkflowTimelineGroup, and WorkflowTimelineFilters are genuinely new: WorkflowTimelineMarker needs its own 8-value WorkflowTimelineEventStatus vocabulary (Pending/Running/Completed/Failed/Cancelled/Blocked/Waiting/Skipped), checked directly against both WorkflowStateValue (no Skipped value) and WorkflowStepperStateValue (a single-cursor \"current\" concept, not a per-event state) before adding a third. WorkflowTimelineEvent is built fresh rather than delegating to Inspector Panel's own InspectorHistory, since InspectorHistory has no connector-line mechanism and no per-entry status marker — though its text layout is deliberately modeled on InspectorHistory's own description/actor/timestamp convention for visual consistency across the two history-rendering surfaces. WorkflowTimelineGroup is new because neither WorkflowStageGroup (lays stages out side by side, not stacked under a shared heading) nor InspectorHistory (a single flat list with no grouping) covers date/category grouping. WorkflowTimelineFilters is modeled directly on Queue & Job's own QueueFilters. Not yet adopted by any real screen — a dedicated audit across six named domains found the one real chronological-list implementation in the codebase (InspectorHistory) already collapsed behind re-exports (StatusTimeline, JobTimeline), not open duplication (see this package's own Promotion Candidates section). Note: a differently-scoped WorkflowTimeline already exists at src/workflows/components/WorkflowTimeline.tsx (the pre-existing Workflow Diagram Library's own animated milestone rail, built on the illustration-canvas TimelineComposition) — documented explicitly in this package's own WorkflowTimeline.tsx doc comment rather than renamed, the same naming-overlap precedent WorkflowProgress.tsx already set.",
    priority: "High",
    requiredStates: ["Pending", "Running", "Completed", "Failed", "Cancelled", "Blocked", "Waiting", "Skipped"],
    requiredVariants: ["Production Timeline", "Publishing Timeline", "Approval Timeline", "Job Timeline", "Activity Timeline", "Audit Timeline", "Grouped Timeline", "Read-only Timeline"],
    accessibility: ["WorkflowTimelineEvent renders a real <button> only when onClick is supplied, never a div-with-onClick", "WorkflowTimelineMarker's icons are all aria-hidden, since the event's own title/description text already carries the meaning", "WorkflowTimelineMarker never relies on marker color alone — Completed/Failed/Blocked/Skipped each pair their tone with a distinct icon, and Waiting uses a dashed border plus a clock icon"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Automation", "Operations", "Audit"],
  },
  {
    id: "approval-review",
    name: "Approval & Review",
    groupId: "workflow",
    purpose: "The standard approval workflow used throughout Production, Publishing, Commerce, Planning, and Intelligence — a request, staged approval steps, a reviewer's own workspace, and a recorded decision, composing Workflow Framework, Workflow Stepper, Workflow Timeline, and Operational Inspector Panel directly rather than duplicating any of them.",
    status: "Exists",
    source: "src/components/workflow/ — built in DS-3.4, the fourth package of the Workflow Component Library. Four of its twelve components are pure re-exports of Workflow Framework's own components (ApprovalFlow=Workflow, ApprovalStage=WorkflowStage, ApprovalActions=WorkflowActions, ReviewSummary=WorkflowSummary) and ReviewPanel is a re-export of Operational Inspector Panel's own InspectorPanel (the same composition Status & Health's StatusPanel already established), chosen over Workflow's own root shell since a review doesn't need Workflow's added sidebar/two-column layout. ApprovalStatus and ApprovalStep need their own 8-value ApprovalStateValue vocabulary (Pending/In Review/Approved/Rejected/Changes Requested/Cancelled/Expired/Completed), checked directly against both WorkflowStateValue (no Rejected/Changes Requested/Expired) and WorkflowStepperStateValue (a single-cursor wizard model with the same gaps) before declaring a third independent type. ApprovalRequest composes Foundation Metadata's own IdentityBlock directly (the same composition WorkflowHeader and InspectorHeader both already use); ApprovalDecision is a thin preset over Foundation Feedback's own Alert (not the EmptyState-based Success/Error/WarningState presets, which are full-region placeholders rather than a compact inline decision record); ReviewComment is a thin preset over Foundation Forms' own TextareaField; ReviewChecklist arranges Foundation Forms' own CheckboxField per item, the same \"arrange existing fields, no new input primitive\" pattern PropertyEditor and FormRow already establish. ReviewHistory composes Workflow Timeline's own WorkflowTimelineGroup/WorkflowTimelineEvent/WorkflowTimelineConnector directly rather than Inspector Panel's InspectorHistory (which has no connector-line mechanism or per-entry status marker, confirmed by its own doc comment), mapping each entry's own ApprovalStateValue onto WorkflowTimelineEventStatus purely for marker/connector rendering while the entry's own title/description text carries the real Approval-specific meaning. Not yet adopted by any real screen — a dedicated audit across six named domains (Production, Publishing, Commerce, Planning, QA, Intelligence) found no existing hand-rolled approval/review/decision component anywhere in the codebase; the design system's own internal inventory had already flagged \"Approval Panel\" as a known, unbuilt gap across three separate prior-session audits, all independently corroborated clean by this package's own audit (see this package's own Promotion Candidates section).",
    priority: "High",
    requiredStates: ["Pending", "In Review", "Approved", "Rejected", "Changes Requested", "Cancelled", "Expired", "Completed"],
    requiredVariants: ["Single Approval", "Multi-stage Approval", "Publishing Review", "Production QA Review", "Commerce Approval", "Checklist Review", "Rejected Review", "Completed Approval"],
    accessibility: ["ApprovalStep renders a real <button> only when onClick is supplied, never a div-with-onClick", "ReviewChecklist's items are real Foundation Forms CheckboxFields with accessibly-associated labels and error text, not custom checkbox markup", "ApprovalStep/ApprovalStatus never rely on marker color alone — each state pairs its tone with a distinct icon or a struck-through label"],
    reuseTargets: ["Production", "Publishing", "Commerce", "Planning", "QA", "Intelligence"],
  },
];

export function maturityFor(component: FoundationComponent): MaturityLevel {
  return MATURITY_FROM_STATUS[component.status];
}

export function groupFor(component: FoundationComponent): FoundationGroupDef {
  const group = FOUNDATION_GROUPS.find((g) => g.id === component.groupId);
  if (!group) throw new Error(`Foundation catalog: unknown group id "${component.groupId}"`);
  return group;
}

export interface CatalogSummary {
  total: number;
  byStatus: Record<InventoryStatus, number>;
  byMaturity: Record<MaturityLevel, number>;
  highPriorityGaps: FoundationComponent[];
}

/** Every number here is computed live from FOUNDATION_COMPONENTS — nothing in this summary is hand-typed. */
export function catalogSummary(): CatalogSummary {
  const byStatus: Record<InventoryStatus, number> = { Exists: 0, Partial: 0, Needed: 0 };
  const byMaturity: Record<MaturityLevel, number> = {
    Concept: 0,
    Prototype: 0,
    "Production Ready": 0,
    Certified: 0,
    Locked: 0,
  };
  for (const component of FOUNDATION_COMPONENTS) {
    byStatus[component.status] += 1;
    byMaturity[maturityFor(component)] += 1;
  }
  const highPriorityGaps = FOUNDATION_COMPONENTS.filter(
    (component) => component.priority === "High" && component.status !== "Exists",
  );
  return { total: FOUNDATION_COMPONENTS.length, byStatus, byMaturity, highPriorityGaps };
}
