export interface CommerceImplementationGuidance {
  label: string;
  text: string;
}

export const IMPLEMENTATION_GUIDANCE: CommerceImplementationGuidance[] = [
  { label: "Platform composition", text: "Every one of these 12 components is a pure re-export over an already-certified Workflow or Operational component — checked directly against Platform Rules (defined in DS-4.1) before writing each file, and in every case an existing component's prop surface already covered the need with no Commerce-specific field required. The same zero-new-wrapper-code precedent Product and Publishing Platform Components already established." },
  { label: "Workflow integration", text: "CommerceFulfillment composes Pipeline Components' own PipelineStage directly for pick/pack/ship stage progression — the same shape ProductionStagePanel already established for Production's own stage-by-stage progress. CommerceInspector composes State Machine directly for a single record's own lifecycle." },
  { label: "Operational integration", text: "CommerceCatalog, CommerceOrders, and CommerceInventory each compose Operational's own DataGrid directly for their own tabular listing — three distinct row shapes (synced products, transactional order records, per-SKU stock levels) composed through the same generic, arbitrary-column component rather than three bespoke tables." },
  { label: "Catalog synchronization", text: "CommerceCatalog does not implement real sync logic, polling, or webhook handling — it renders whatever columns and rows the caller supplies through Data Grid's own controlled props, including a per-row sync-status column when needed. Whether a catalog entry is actually in sync with its source is Business Feature logic, not something this platform component decides." },
  { label: "Order lifecycle", text: "CommerceOrders composes Data Grid rather than Queue, deliberately: an order is a structured transactional record (line items, total, ship-to), not a job-in-flight with priority and processed-of-total progress the way ProductionQueue/PublishingQueue's own jobs are. Whether an order is actually fulfilled is Business Feature logic." },
  { label: "Inventory management", text: "CommerceInventory renders whatever SKU/quantity/location columns the caller supplies through Data Grid — it does not implement stock math, reservation logic, or reorder-threshold checks itself." },
  { label: "Fulfillment flow", text: "CommerceFulfillment's own children slot is where WorkflowStep content belongs for each pick/pack/ship stage, the same composition pattern ProductionStagePanel's own gallery already established — the shell holds no business logic about stage ordering or gating." },
  { label: "Pricing presentation", text: "CommercePricing's own children slot is where PropertyRow/PropertyNumber content belongs for base price, sale price, and currency — checked directly and confirmed neither PropertyNumber nor any Property-family component has a first-class currency-symbol/formatting field; currency is expressed through the field's own label (e.g. \"Base Price (USD)\") rather than a dedicated prop, a disclosed gap rather than an invented one." },
];
